
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  packages: !include_dir_named packages

automation: !include_dir_merge_list automations/
frontend:
  themes: !include_dir_merge_named themes

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

python_script:

# Text to speech
tts:
  - platform: google_translate

recorder:
  db_url: !secret recorder_url
  purge_keep_days: 30
  commit_interval: 120
  exclude:
    domains:
      - automation
      - updater
      - timer
    entities:
      - binary_sensor.updater
      - sensor.last_boot
      - binary_sensor.mi_9t_is_charging
      - camera.buienradar_loop
      - weather.pw_casa_hourly
    entity_globs:
      - sensor.*absolute_humidity
      - sensor.*estimated_current
      - sensor.*_wled_free_memory
      - sensor.*_wled_wi_fi_bssid
      - sensor.*_wled_uptime
      - sensor.*_wled_wi_fi_channel
      - sensor.mi_9t*
      - sensor.*presence
      - input_number.electricity_*
      - input_number.forecast_*
      - input_text.forecast_*
    event_types:
      - call_service # Don't record service calls


influxdb:
  host: 192.168.0.17
  port: 8086
  api_version: 2
  token: !secret influx_token
  organization: homeassistant
  bucket: homeassistant/hass_1y
  ssl: false
  verify_ssl: false
  max_retries: 5
  include:
    entities:
      - counter.dsmr_reconnect
      - weather.pw_casa
      - device_tracker.mi_9t
    domains:
      - sensor
      - climate
  exclude:
    domains:
      - camera
      - binary_sensor
      - persistent_notification
      - zone
      - switch
      - scene
      - device_tracker
    entities:
      - sensor.last_boot
      - sensor.washing_machine_status
      - sensor.dryer_status
      - sensor.dish_washer_status
    entity_globs:
      - sensor.*absolute_humidity
      - sensor.*estimated_current
      - sensor.*_wled_free_memory
      - sensor.*_wled_wi_fi_bssid
      - sensor.*_wled_uptime
      - sensor.*_wled_wi_fi_channel
      - sensor.mi_9t*
      - sensor.*presence
      - sensor.foscam_r2m_1_log*


device_tracker:
  - platform: bluetooth_le_tracker
    interval_seconds: 30
    consider_home: 240
    new_device_defaults:
      track_new_devices: false
  - platform: ping
    hosts:
      pwnitrogen: 192.168.0.101
#      hasspi: 192.168.0.16
