---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   01/2022
#   @package        :   Global switches
#   @description    :   The master switch
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################
input_boolean:
  # The master switch acts as a sort of home/not-home switch.
  # It decouples zones/presence from automations.
  # If it's off, then most automations won't do anything.
  # If it's turned off, it still needs a scene to turn off the lights.
  master_switch:
    name: Master switch
    icon: mdi:light-switch

automation:
  - id: general_master_switch_turn_on
    alias: Switches - Master switch on
    description: Turn on the master switch when somebody from the household members comes home
    trigger:
      - platform: state
        entity_id: group.household_members
        to: home
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: TURN_MASTER_SWITCH_ON
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.master_switch

  - id: general_master_switch_turn_on_on_wifi
    alias: Switches - Master switch on on wifi change
    description: Turn on the master switch when phone connects to Wifi
    trigger:
      - platform: state
        entity_id: sensor.mi_9t_wifi_connection
        to: !secret wifi_ssid_2_4G
      - platform: state
        entity_id: sensor.mi_9t_wifi_connection
        to: !secret wifi_ssid_5G
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state: Day
      - condition: template
        alias: Do not trigger 10 minutes after changing the master state
        value_template: >
            {% set ignore_ts = (now().timestamp() - 600)|as_datetime %}
            {% set last_triggered_at = states.input_boolean.master_switch.last_updated %}
            {% set limit = last_triggered_at <= ignore_ts %}
            {{ limit }}
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.master_switch

  - id: general_master_switch_turn_off
    alias: Switches - Master switch off
    description: Turn off the master switch when everybody from the household members left
    trigger:
      - platform: state
        entity_id: group.household_members
        to: not_home
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.master_switch
