---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   04/2021
#   @package        :   Everything off
#   @description    :   Turns everything off in one action
#   @url            :   https://codeberg.org/PW999/home-assistant-config/
###############################################################################

automation:
  - id: general_everything_off
    alias: Global - Turn lights off
    description: If master switch is turned off
    trigger:
      - entity_id: input_boolean.master_switch
        platform: state
        to: "off"
      - entity_id: input_select.home_mode
        platform: state
    condition:
      - condition: state
        entity_id: input_boolean.master_switch
        state: "off"
    action:
      - if:
          # Night scene has all lights off exception some very dim light in the living room for my cat
          - condition: state
            entity_id: input_select.home_mode
            state: Night
        then:        
          - service: scene.turn_on
            entity_id: scene.home_off_night
            data:
              transition: 4
        else:
            - service: scene.turn_on
              entity_id: scene.home_off
              data:
                transition: 2

scene:
  - id: general_everything_off_scene_night
    name: Home Off Night
    entities:
      light.front_window:
        state: "off"
      light.living_room_tv:
        state: "off"
      light.living_room_big:
        state: "on"
        brightness: 0
      light.living_room_small:
        state: "on"
        brightness: 12
        color_temp: 280
      light.bureau_wled_master:
        state: "off"
      light.hall_1:
        state: "off"
      light.hall_2:
        state: "off"
      light.hall_3:
        state: "off"
      light.bathroom_light:
        state: "off"
      switch.gosund_sp112_4_usb:
        state: "off"
      switch.bathroom_fan_switch:
        state: "off"

  - id: general_everything_off_scene
    name: Home Off
    entities:
      light.front_window:
        state: "off"
      light.living_room_tv:
        state: "off"
      light.living_room_big:
        state: "off"
      light.living_room_small:
        state: "off"
      light.bureau_wled_master:
        state: "off"
      light.hall_1:
        state: "off"
      light.hall_2:
        state: "off"
      light.hall_3:
        state: "off"
      light.bathroom_light:
        state: "off"
      switch.gosund_sp112_4_usb:
        state: "off"
      switch.bathroom_fan_switch:
        state: "off"
