---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   04/2022
#   @package        :   Android alarm trigger
#   @description    :   Triggers the master switch on next companion alarm
#   @url            :   https://github.com/PW999/home-assistant-config/
#   @credit         :   https://community.home-assistant.io/t/how-to-use-next-alarm-sensor/221686/14
###############################################################################
input_datetime:
  wakeup_alarm:
    name: Wakeup Alarm Time
    has_time: true
    has_date: true
    icon: mdi:android

automation:
  - id: general_wakeup_delay_set_wakeup_alarm_time
    alias: Wakeup - Delay set wakeup alarm time
    trigger:
      platform: state
      entity_id: sensor.pwxperia10iv_next_alarm
    mode: restart
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.pwxperia10iv_next_alarm
            state:
              - unavailable
              - unknown
    action:
      - delay: 00:45:00
      - service: input_datetime.set_datetime
        entity_id: input_datetime.wakeup_alarm
        data_template:
          datetime: "{{ strptime(state_attr('sensor.pwxperia10iv_next_alarm', 'Local Time'), '%a %b %d %H:%M:%S %Z%z %Y') }}"

  - id: general_wakeup_turn_on_master_switch
    alias: Wakeup - Turn on master switch
    trigger:
      platform: time
      at: input_datetime.wakeup_alarm
    condition:
      - condition: time # can't use the generate morning state since this won't trigger in the winter (it might still be night)
        before: "09:00:00"
      - condition: not
        conditions:
          - condition: state # since my alarm will go off too early anyway
            entity_id: input_select.presence_mode
            state: "WFH"
          - condition: state # this is actual vacation (I'm gone, not at home)
            entity_id: input_select.presence_mode
            state: "Vacation"
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.master_switch

  - id: general_wakeup_turn_on_master_switch_wfh
    alias: Wakeup - Turn on master switch when working from home
    trigger:
      platform: time
      at: "07:45:00"
    condition:
      - condition: state
        entity_id: input_select.presence_mode
        state: "WFH"
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.master_switch
