---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   01/2022
#   @package        :   Temperature offset
#   @description    :   Fix temp difference between Aqara and Osram sensor
#   @url            :   https://github.com/PW999/home-assistant-config/
#   @template:      :   ./sensor/sensor_toilet_temperature.erb
###############################################################################

sensor:
  - platform: template
    sensors:
      toilet_temperature_corrected:
        friendly_name: Toilet temperature
        unit_of_measurement: °C
        device_class: temperature
        availability_template: "{{ not is_state('sensor.toilet_presence', 'unavailable')  }}"
        value_template: "{{ (float(states('sensor.toilet_presence')) + 0.4) | round(1) }}"
