---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   01/2022
#   @package        :   Roomba automation
#   @description    :   Keep track of last Roomba clean
#   @url            :   https://github.com/PW999/home-assistant-config/
#   @credit         :   https://community.home-assistant.io/t/scheduled-timeslot-automation-e-g-vacuum/259147/3
###############################################################################

input_datetime:
  roomba_last_clean:
    name: Last time Roomba did a clean job
    has_date: true
    has_time: true

automation:
  - id: roomba_last_clean_timestamp
    alias: Roomba - Update last clean timestamp
    description: Update input with the last time Roomba started cleaning even if started from app
    trigger:
      - platform: state
        entity_id: vacuum.pwroomba
        to: cleaning
    action:
      - service: input_datetime.set_datetime
        data:
          entity_id: input_datetime.roomba_last_clean
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"