---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   01/2023
#   @package        :   Afvalbeheer
#   @description    :   Adds waste management reminders
#   @url            :   https://github.com/PW999/home-assistant-config/
#   @credit         :   https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer
###############################################################################

afvalbeheer:
  wastecollector: RecycleApp
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: !secret postcode
  streetnumber: 1
  streetname: !secret street
  upcomingsensor: 1
  dateobject: 1
  builtinicons: 1
  builtiniconsnew: 1
  dutch: 0
  updateinterval: 24

automation:
  - id: afvalbeheer_notification_on_resource
    alias: Afvalbeheer - Notification on resource
    trigger:
      - platform: state
        entity_id: sensor.recycleapp_tomorrow
        from: "None"
        for: "17:00:00"
    condition:
      - alias: "Not grofvuil or kerstboom"
        condition: template
        value_template: >
          {% if 'grofvuil' in trigger.to_state.state %}
          false
          {% elif 'kerstboom' in trigger.to_state.state %}
          false
          {% else %}
          true
          {% endif %}
    action:
      - service: notify.mobile_app_mi_9t
        data:
          message: |
            Tomorrow we must put {{ trigger.to_state.state }} outside
          title: Waste
