---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   02/2025
#   @package        :   Waze dynamic refresh interval
#   @description    :   Dynamic refresh interval for waze travel time
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################

automation:
  - id: waze_normal_update
    alias: Waze - Normal update interval
    description: Polls waze every 5 minutes when I have to go to work or go home
    triggers:
      - trigger: time_pattern
        minutes: "/5"
        hours: "6"
      - trigger: time_pattern
        minutes: "/5"
        hours: "7"
      - trigger: time_pattern
        minutes: "/5"
        hours: "15"
      - trigger: time_pattern
        minutes: "/5"
        hours: "16"
    conditions:
      - alias: "Only when I have to go to work"
        condition: state
        entity_id: input_select.presence_mode
        state: "Workday"
    actions:
      - action: homeassistant.update_entity
        target:
          entity_id:
          - sensor.to_work
          - sensor.to_home

  - id: waze_slow_update
    alias: Waze - Slow update interval
    description: Polls waze every 20 minutes when I don't have to go work
    triggers:
      - trigger: time_pattern
        minutes: "/20"
    conditions:
      - condition: not
        conditions:
        - alias: "Only when I have to go to work"
          condition: state
          entity_id: input_select.presence_mode
          state: "Workday"
    actions:
      - action: homeassistant.update_entity
        target:
          entity_id:
          - sensor.to_work
          - sensor.to_home