---

# ##############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   01/2022
#   @package        :   Fridge package
#   @description    :   Monitor fridge and notify when it is turned off
#   @url            :   https://github.com/PW999/home-assistant-config/
#   @credit         :   https://github.com/stanvx/Home-Assistant-Configuration/blob/master/packages/washing_machine.yaml
#   @erb            :   ./appliance/template/appliance_fridge.erb
# ##############################################################################
homeassistant:
  customize:
    sensor.gosund_sp112_2_current:
      friendly_name: Fridge Current
    switch.gosund_sp112_2_main_relay:
      friendly_name: Fridge Switch
    switch.gosund_sp112_2_usb:
      friendly_name: Fridge Usb Switch
    sensor.gosund_sp112_2_rrsi:
      friendly_name: Fridge RSSI
    sensor.gosund_sp112_2_total_daily_energy_consumption:
      friendly_name: Fridge today's energy consumption
    sensor.gosund_sp112_2_uptime:
      friendly_name: Fridge Uptime
    sensor.gosund_sp112_2_voltage:
      friendly_name: Fridge Voltage
    sensor.gosund_sp112_2_wattage:
      friendly_name: Fridge Power Consumption
    sensor.gosund_sp112_2_consumption:
      friendly_name: Fridge total energy consumption

automation:
  # Just make sure that the power plug of the fridge is always on !
  - id: appliance_fridge_keep_power_on
    alias: Fridge - Always keep power on
    trigger:
      - platform: time_pattern
        minutes: /10
      - platform: state
        entity_id: switch.gosund_sp112_2_main_relay
        to: "off"
      - platform: state
        entity_id: switch.gosund_sp112_2_main_relay
        to: unavailable
        for: "00:02:00"
    condition:
      - alias: Fridge power was off
        condition: state
        entity_id: switch.gosund_sp112_2_main_relay
        state: "off"
    action:
      - alias: Turn on the fridge's power
        service: switch.turn_on
        target:
          entity_id: switch.gosund_sp112_2_main_relay
      - service: notify.mobile_app_mi_9t
        data:
          message: |
            Fridge power was off !
          title: Fridge alert
