---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   04/2021
#   @package        :   Weather package
#   @description    :   Small weather related actions
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################

input_number:
  # We only have next day's weather forecast, so before midnight, we record next day's
  # forecast so that in the morning we can send the forcast of today through notification
  forecast_temp:
    name: Weather forecast temperature
    min: -50
    max: 50
    step: 0.1
    unit_of_measurement: °C
  forecast_min_temp:
    name: Weather forecast low temperature
    min: -50
    max: 50
    step: 0.1
    unit_of_measurement: °C
  forecast_precip:
    name: Weather forecast precipitation
    min: 0
    max: 100
    step: 0.1
    unit_of_measurement: mm

input_text:
  weather_forecast:
    name: Weather forecast
    icon: mdi:cloud-outline

automation:
  - id: weather_save_next_day_forecast
    alias: Forecast - Save tomorrow weather
    description: Save's tomorrow's forecast so we can use it the next day as today's forecast
    trigger:
      - platform: time
        at: "22:00:00"
    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.weather_forecast
          value: "{{ state_attr('weather.pw_casa', 'forecast')[0].condition }}"
      - service: input_number.set_value
        data:
          entity_id: input_number.forecast_min_temp
          value: "{{ state_attr('weather.pw_casa', 'forecast')[0].templow | float }}"
      - service: input_number.set_value
        data:
          entity_id: input_number.forecast_precip
          value: "{{ state_attr('weather.pw_casa', 'forecast')[0].precipitation | float }}"
      - service: input_number.set_value
        data:
          entity_id: input_number.forecast_temp
          value: "{{ state_attr('weather.pw_casa', 'forecast')[0].temperature | float }}"
