###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   04/2021
#   @package        :   General System Configuration
#   @description    :   Contains system related sensors and automations
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################

automation:
  - id: '8000000000015'
    alias: Button - Toggle evening lights
    description: Use center button to toggle evening mode
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: 'lightify_switch_mini_27'
          event: 3002
    condition:
      - condition: state
        entity_id: input_boolean.master_switch
        state:  'on'
    action:
      - service: input_boolean.toggle
        data:
          entity_id: input_boolean.dusk_till_dawn
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.dimm_lights


  - id: '8000000000016'
    alias: Button - Toggle dimmed lights
    description: Use down button to turn on evening mode and toggle dimmed mode
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: 'lightify_switch_mini_27'
          event: 2002
    condition:
      - condition: state
        entity_id: input_boolean.master_switch
        state:  'on'
    action:
      - service: input_boolean.toggle
        data:
          entity_id: input_boolean.dimm_lights
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.dusk_till_dawn
