---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   01/2022
#   @package        :   Very sunny
#   @description    :   Contains a template to indicate it's very sunny (to turn of lights and stuff)
#   @url            :   https://github.com/PW999/home-assistant-config/
#   @credit         :   https://community.home-assistant.io/t/scheduled-timeslot-automation-e-g-vacuum/259147/3
###############################################################################

sensor:
  - platform: template
    sensors:
      very_sunny:
        friendly_name: Very sunny
        availability_template: >-
            {{ not (
                  is_state('weather.pw_casa', 'unavailable')
                  or is_state('weather.pw_casa', 'unknown')
                  or is_state('sensor.season', 'unavailable')
                  or is_state('sensor.season', 'unknown')
                )
            }}
        value_template: >-
            {{
              is_state('sensor.season', 'summer') and is_state('weather.pw_casa', 'sunny')
            }}
