---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   01/2022
#   @package        :   System sensors
#   @description    :   Contains system related sensors
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use_percent
        arg: /config
      - type: processor_use
      - type: last_boot
