---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   08/2023
#   @package        :   Influx sensors
#   @description    :   Fetch data from Influx2 as sensor
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################

homeassistant:
  customize:
    sensor.pve2_cpu_package_temperature:
      icon: mdi:thermometer
    sensor.pve2_cpu_package_power:
      icon: mdi:cpu-64-bit
    sensor.pve2_nvme_temperature:
      icon: mdi:thermometer
    sensor.pve2_sda_temperature:
      icon: mdi:thermometer
    sensor.pve2_cpu_usage:
      icon: mdi:cpu-64-bit
    sensor.pve2_mem_free:
      icon: mdi:memory
    sensor.pve2_local_free:
      icon: mdi:harddisk
    sensor.pve2_local_lvm_free:
      icon: mdi:harddisk
    sensor.pve2_synology_free:
      icon: mdi:nas

sensor:
  - platform: influxdb
    api_version: 2
    host: lxc-influx-01.pwcasa.internal
    port: 443
    ssl: true
    ssl_ca_cert: /config/ssl/ca_certificate.crt
    organization: telegraf
    bucket: telegraf
    token: !secret influx_telegraf_token
    queries_flux:
      - group_function: max
        name: "pve2 CPU package temperature"
        unique_id: pve2_cpu_package_temperature
        unit_of_measurement: °C
        query: >
          filter(fn: (r) => r["_measurement"] == "sensors")
          |> filter(fn: (r) => r["_field"] == "temp_input")
          |> filter(fn: (r) => r["chip"] == "coretemp-isa-0000")
          |> filter(fn: (r) => r["feature"] == "package_id_0")
          |> filter(fn: (r) => r["host"] == "pve2.pwcasa.internal")
        range_start: "-2m"
      - group_function: max
        name: "pve2 NVMe temperature"
        unique_id: pve2_nvme_temperature
        unit_of_measurement: °C
        imports:
          - math
        query: >
          filter(fn: (r) => r["_measurement"] == "sensors")
          |> filter(fn: (r) => r["_field"] == "temp_input")
          |> filter(fn: (r) => r["chip"] == "nvme-pci-3a00")
          |> filter(fn: (r) => r["feature"] == "sensor_1")
          |> filter(fn: (r) => r["host"] == "pve2.pwcasa.internal")
          |> map(fn: (r) => ({ r with _value: math.round(x: r._value) }))
        range_start: "-2m"
      - group_function: max
        name: "pve2 CPU Package power"
        unique_id: pve2_cpu_package_power
        unit_of_measurement: W
        query: >
          filter(fn: (r) => r["_measurement"] == "powerstat_package")
          |> filter(fn: (r) => r["_field"] == "current_power_consumption_watts")
          |> filter(fn: (r) => r["host"] == "pve2.pwcasa.internal")
          |> group(columns: ["host"])
          |> aggregateWindow(every: 10s, fn: sum, createEmpty: false)
        range_start: "-2m"
  - platform: influxdb
    api_version: 2
    host: lxc-influx-01.pwcasa.internal
    port: 443
    ssl: true
    ssl_ca_cert: /config/ssl/ca_certificate.crt
    organization: proxmox
    bucket: proxmox
    token: !secret influx_proxmox_token
    queries_flux:
      - group_function: max
        name: "pve2 CPU usage"
        unique_id: pve2_cpu_usage
        unit_of_measurement: "%"
        imports:
          - math
        query: >
          filter(fn: (r) => r["_measurement"] == "cpustat")
          |> filter(fn: (r) => r["host"] == "pve2")
          |> filter(fn: (r) => r["_field"] == "cpu")
          |> map(fn: (r) => ({ r with _value: math.round(x: r._value * 100.0) }))
        range_start: "-2m"
      - group_function: min
        name: "pve2 Memory free"
        unique_id: pve2_mem_free
        unit_of_measurement: "GB"
        imports:
          - math
        query: >
          filter(fn: (r) => r["_measurement"] == "memory")
          |> filter(fn: (r) => r["_field"] == "memfree")
          |> filter(fn: (r) => r["host"] == "pve2")
          |> map(fn: (r) => ({ r with _value: math.round(x: 10.0 * r._value / (1024.0*1024.0*1024.0)) / 10.0 }))
        range_start: "-20m"
      - group_function: min
        name: "pve2 local free"
        unique_id: pve2_local_free
        unit_of_measurement: "GB"
        imports:
          - math
        query: >
          filter(fn: (r) => r["_measurement"] == "system")
          |> filter(fn: (r) => r["_field"] == "avail")
          |> filter(fn: (r) => r["host"] == "local")
          |> filter(fn: (r) => r["nodename"] == "pve2")
          |> map(fn: (r) => ({ r with _value: math.round(x: 10.0 * r._value / (1024.0*1024.0*1024.0)) / 10.0 }))
        range_start: "-20m"
      - group_function: min
        name: "pve2 local-lvm free"
        unique_id: pve2_local_lvm_free
        unit_of_measurement: "GB"
        imports:
          - math
        query: >
          filter(fn: (r) => r["_measurement"] == "system")
          |> filter(fn: (r) => r["_field"] == "avail")
          |> filter(fn: (r) => r["host"] == "local-lvm")
          |> filter(fn: (r) => r["nodename"] == "pve2")
          |> map(fn: (r) => ({ r with _value: math.round(x: 10.0 * r._value / (1024.0*1024.0*1024.0)) / 10.0 }))
        range_start: "-20m"
      - group_function: min
        name: "pve2 synology free"
        unique_id: pve2_synology_free
        unit_of_measurement: "GB"
        imports:
          - math
        query: >
          filter(fn: (r) => r["_measurement"] == "system")
          |> filter(fn: (r) => r["_field"] == "avail")
          |> filter(fn: (r) => r["host"] == "pwsynology")
          |> filter(fn: (r) => r["nodename"] == "pve2")
          |> map(fn: (r) => ({ r with _value: math.round(x: 10.0 * r._value / (1024.0*1024.0*1024.0)) / 10.0 }))
        range_start: "-20m"
