---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   01/2022
#   @package        :   Season
#   @description    :   Adds the season integration
#   @url            :   https://github.com/PW999/home-assistant-config/
#   @credit         :   https://community.home-assistant.io/t/scheduled-timeslot-automation-e-g-vacuum/259147/3
###############################################################################

sensor:
  - platform: season
    type: meteorological
