---
# ##############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   01/2022
#   @package        :   Work package
#   @description    :   Small work related actions
#   @url            :   https://codeberg.org/PW999/home-assistant-config/
# ##############################################################################

timer:
  workday_countdown:
    name: Workday countdown
    duration: "08:00:00"

automation:
  - id: workday_timer_start
    alias: Workday - Start at work timer
    description: Starts timer when I arrive at work or start my work laptop
    triggers:
      - trigger: zone
        entity_id:
          - person.phillip
        zone: zone.work
        event: enter
      - trigger: state
        entity_id:
          - device_tracker.as_hq_lt_108
        to: home
    conditions:
      - condition: state
        entity_id: timer.workday_countdown
        state: idle
    actions:
      - delay: 300 # Zone is pretty big, gotta park my car and stuff
      - action: timer.start
        data:
          entity_id: timer.workday_countdown

  - id: workday_timer_cancel
    alias: Workday - Stop at work timer
    description: Stops the timer when I leave work or if my laptop is off
    triggers:
      - trigger: zone
        entity_id:
          - person.phillip
        zone: zone.work
        event: leave
      - trigger: state
        entity_id:
          - device_tracker.as_hq_lt_108
        to: away
        for: "00:20:00" # bluetooth tracking is not so accurate
    conditions:
      - condition: state
        entity_id: timer.workday_countdown
        state: active
    action:
      - action: timer.cancel
        data:
          entity_id: timer.workday_countdown

  - id: workday_timer_finished
    alias: Workday - travel to home time notification
    description: Send travel to home time when I'm at work for 8h
    mode: single
    triggers:
      - trigger: event
        event_type: timer.finished
        event_data:
          entity_id: timer.workday_countdown
    actions:
      - action: notify.mobile_app_pwxperia10iv
        data:
          message: |
            Almost time to go home, travel time is {{ states('sensor.to_home') }} {{ state_attr('sensor.to_home', 'unit_of_measurement') }} via {{ state_attr('sensor.to_home', 'route') }}
          title: Almost time to stop
      - delay: 600
