---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   19/06/2022
#   @package        :   Bathroom light automation
#   @description    :   Automates the Ikea light in my bathroom
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################

timer:
  bathroom_light_extended_time:
    name: Bathroom light extended timer
    duration: "00:15:00"

input_boolean:
  bathroom_light_increase_brightness:
    name: Bathroom on switch pressed continuously
    initial: false
  bathroom_light_decrease_brightness:
    name: Bathroom off switch pressed continuously
    initial: false

automation:
  - id: light_bathroom_turn_on
    alias: Bathroom - turn light on
    description: Turn on the light in the bathroom on motion
    trigger:
      - entity_id: binary_sensor.bathroom_presence
        platform: state
        to: "on"
    condition:
      - condition: state
        entity_id: light.bathroom_light
        state: "off"
    action:
      - if: # during the day when master is on
          - condition: state
            entity_id: input_select.home_mode
            state: Day
          - condition: state
            entity_id: input_boolean.master_switch
            state: "on"
        then:
          - service: light.turn_on
            data:
              color_temp: 330
              brightness: 255
            target:
              entity_id: light.bathroom_light
        else:
          - if: # at night when the master is off (I'm asleep)
              - condition: state
                entity_id: input_select.home_mode
                state: Night
              - condition: state
                entity_id: input_boolean.master_switch
                state: "off"
            then:
              - service: light.turn_on
                data:
                  color_temp: 380
                  brightness: 96
                target:
                  entity_id: light.bathroom_light
            else:
              - if: # morning/evening when I'm home
                  - condition: state
                    entity_id: input_boolean.master_switch
                    state: "on"
                then:
                  - service: light.turn_on
                    data:
                      color_temp: 330
                      brightness: 224
                    target:
                      entity_id: light.bathroom_light

  - id: light_bathroom_turn_off
    alias: Bathroom - turn light off
    description: Turn off the light
    trigger:
      - entity_id: binary_sensor.bathroom_presence
        platform: state
        to: "off"
        for: "00:04:00"
      - entity_id: light.bathroom_light
        platform: state
        to: "on"
        for: "00:30:00" # sometimes it just keeps on for no reason (thanks Ikea)
      - entity_id: timer.bathroom_light_extended_time
        platform: state
        to: idle
    condition:
      - condition: state
        entity_id: timer.bathroom_light_extended_time
        state: idle
      - entity_id: binary_sensor.bathroom_presence
        condition: state
        state: "off"
    action:
      - service: light.turn_off
        target:
          entity_id: light.bathroom_light

  - id: light_bathroom_start_extended_timer
    alias: Bathroom - Start extended timer
    description: Start extended light timer in case I want to shower (can't detection motion in the shower)
    trigger:
      - platform: device
        device_id: 38c1a38ab3652833a89847b70a2e1a2a
        domain: deconz
        type: remote_button_short_press
        subtype: turn_on
    action:
      - service: light.turn_on
        data:
          flash: short
        target:
          entity_id: light.bathroom_light
      - service: timer.cancel
        target:
          entity_id: timer.bathroom_light_extended_time
      - service: timer.start
        target:
          entity_id: timer.bathroom_light_extended_time

  - id: switch_bathroom_on_continuous
    alias: Bathroom - On switch pressed continuously
    description: When pressing the on button continously, enable boolean which will increase brightness
    trigger:
      - device_id: 38c1a38ab3652833a89847b70a2e1a2a
        domain: deconz
        platform: device
        type: remote_button_long_press
        subtype: turn_on
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.bathroom_light_decrease_brightness
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.bathroom_light_increase_brightness

  - id: switch_bathroom_off_continuous
    alias: Bathroom - Off switch pressed continuously
    description: When pressing the off button continously, enable boolean which will decrease brightness
    trigger:
      - device_id: 38c1a38ab3652833a89847b70a2e1a2a
        domain: deconz
        platform: device
        type: remote_button_long_press
        subtype: turn_off
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.bathroom_light_decrease_brightness
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.bathroom_light_increase_brightness

  - id: switch_bathroom_continuous_released
    alias: Bathroom - Switch no longer pressed continuously
    description: When no longer pressing the button continously, disable booleans which will change brightness
    trigger:
      - device_id: 38c1a38ab3652833a89847b70a2e1a2a
        domain: deconz
        platform: device
        type: remote_button_long_release
        subtype: turn_on
      - device_id: 38c1a38ab3652833a89847b70a2e1a2a
        domain: deconz
        platform: device
        type: remote_button_long_release
        subtype: turn_off
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.bathroom_light_decrease_brightness
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.bathroom_light_increase_brightness

  - id: bathroom_light_change_brightness
    alias: Bathroom - Change bathroom light brightness
    trigger:
      - entity_id: input_boolean.bathroom_light_increase_brightness
        platform: state
        to: "on"
      - entity_id: input_boolean.bathroom_light_decrease_brightness
        platform: state
        to: "on"
    action:
      if:
        - condition: state
          entity_id: input_boolean.bathroom_light_increase_brightness
          state: "on"
      then:
        - repeat:
            until:
              - condition: state
                entity_id: input_boolean.bathroom_light_increase_brightness
                state: "off"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.bathroom_light
                data:
                  brightness_step: 2
      else: # kind of implies that the decrease boolean is on
        - repeat:
            until:
              - condition: state
                entity_id: input_boolean.bathroom_light_decrease_brightness
                state: "off"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.bathroom_light
                data:
                  brightness_step: -2

  - id: switch_bathroom_auto_reset
    alias: Bathroom - Reset continuous on booleans
    trigger:
      - entity_id: input_boolean.bathroom_light_increase_brightness
        platform: state
        to: "on"
        for: "00:01:00"
      - entity_id: input_boolean.bathroom_light_decrease_brightness
        platform: state
        to: "on"
        for: "00:01:00"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.bathroom_light_decrease_brightness
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.bathroom_light_increase_brightness
