---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   19/06/2022
#   @package        :   Bathroom light automation
#   @description    :   Automates the Ikea light in my bathroom
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################

timer:
  # Motion detection doesn't work when I'm in the shower
  bathroom_light_extended_time:
    name: Bathroom light extended timer
    duration: "00:25:00"

automation:
  - id: light_bathroom_turn_on
    alias: Bathroom - turn light on
    description: Turn on the light in the bathroom on motion
    trigger:
      - entity_id: binary_sensor.bathroom_presence
        platform: state
        to: "on"
    condition:
      - condition: state
        entity_id: light.bathroom_light
        state: "off"
    action:
      - if: # during the day when master is on
          - condition: state
            entity_id: input_select.home_mode
            state: Day
          - condition: state
            entity_id: input_boolean.master_switch
            state: "on"
        then:
          - service: light.turn_on
            data:
              color_temp: 285
              brightness: 255
            target:
              entity_id: light.bathroom_light
        else:
          - if: # at night or morning when the master is off (I'm asleep)
              - condition: state
                entity_id: input_select.home_mode
                state:
                  - Night
                  - Morning
              - condition: state
                entity_id: input_boolean.master_switch
                state: "off"
            then:
              - service: light.turn_on
                data:
                  color_temp: 420
                  brightness: 96
                target:
                  entity_id: light.bathroom_light
            else:
              - if: # morning/evening when I'm home
                  - condition: state
                    entity_id: input_boolean.master_switch
                    state: "on"
                then:
                  - service: light.turn_on
                    data:
                      color_temp: 330
                      brightness: 224
                    target:
                      entity_id: light.bathroom_light

  - id: light_bathroom_turn_off
    alias: Bathroom - turn light off
    description: Turn off the light
    trigger:
      - entity_id: binary_sensor.bathroom_presence
        platform: state
        to: "off"
        for: "00:04:00"
      - entity_id: binary_sensor.bathroom_presence
        platform: state
        to: "off"
        for: "00:06:00" # second attempt if Ikea missed it
      - entity_id: light.bathroom_light
        platform: state
        to: "on"
        for: "00:30:00" # sometimes it just keeps on for no reason (thanks Ikea)
      - entity_id: timer.bathroom_light_extended_time
        platform: state
        to: idle
    condition:
      - condition: state
        entity_id: timer.bathroom_light_extended_time
        state: idle
      - entity_id: binary_sensor.bathroom_presence
        condition: state
        state: "off"
    action:
      - service: light.turn_off
        target:
          entity_id: light.bathroom_light

  - id: light_bathroom_start_extended_timer
    alias: Bathroom - Start extended timer
    description: Start extended light timer in case I want to shower (can't detection motion in the shower)
    trigger:
      - platform: device
        device_id: 38c1a38ab3652833a89847b70a2e1a2a
        domain: deconz
        type: remote_button_short_press
        subtype: turn_on
    action:
      - service: timer.cancel
        target:
          entity_id: timer.bathroom_light_extended_time
      - service: timer.start
        target:
          entity_id: timer.bathroom_light_extended_time
      - service: light.turn_on
        data:
          flash: short
        target:
          entity_id: light.bathroom_light
