---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   05/2021
#   @package        :   General hall light automation
#   @description    :   Presence based hall lights
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################

automation:
  - id: light_hall_presence
    alias: Hall presence detected
    description: Increase hall brightness when presence is detected
    trigger:
      - entity_id: binary_sensor.hall_presence
        platform: state
        to: "on"
      - entity_id: binary_sensor.pantry_door
        platform: state
        to: "off"
      - entity_id: input_boolean.master_switch
        platform: state
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.master_switch
        state: "on"
      - condition: state
        entity_id: binary_sensor.hall_presence
        state: "on"
    action:
      - if:
          - condition: state
            entity_id: input_select.home_mode
            state: Day
        then:
          - service: scene.turn_on
            entity_id: scene.hall_100
        else:
          - service: scene.turn_on
            entity_id: scene.hall_50

  - id: light_hall_presence_night
    alias: Hall presence detected during night
    description: Turn on a little light during the night when presence detected
    trigger:
      - entity_id: binary_sensor.hall_presence
        platform: state
        to: "on"
      - entity_id: binary_sensor.pantry_door
        platform: state
        to: "off"
    condition:
      - condition: state
        entity_id: binary_sensor.hall_presence
        state: "on"
      - condition: state
        entity_id: input_boolean.master_switch
        state: "off"
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.home_mode
            state: Day
    action:
      - service: scene.turn_on
        entity_id: scene.hall_night

  ## SENSOR CLEAR ##
  - id: light_hall_clear
    alias: Hall no presence
    description: Keep a dim light on during the day when no presence is detected
    trigger:
      - entity_id: binary_sensor.hall_presence
        platform: state
        to: "off"
        for: "00:01:00"
      - entity_id: input_boolean.master_switch
        platform: state
        to: "on"
      - entity_id: binary_sensor.pantry_door
        platform: state
        to: "off"
      - platform: state
        entity_id: input_select.home_mode
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.home_mode
            state: Night
      - condition: state
        entity_id: binary_sensor.hall_presence
        state: "off"
      - condition: state
        entity_id: input_boolean.master_switch
        state: "on"
    action:
      - service: scene.turn_on
        entity_id: scene.hall_25
        data:
          transition: 3

  - id: light_hall_off_night
    alias: Hall off at night
    description: Turn the lights off when it's night
    trigger:
      - entity_id: binary_sensor.hall_presence
        platform: state
        to: "off"
      - entity_id: binary_sensor.pantry_door
        platform: state
        to: "off"
      - entity_id: input_boolean.master_switch
        platform: state
        to: "off"
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state: Night
      - condition: state
        entity_id: binary_sensor.hall_presence
        state: "off"
      - condition: state
        entity_id: input_boolean.master_switch
        state: "off"
    action:
      - service: scene.turn_on
        entity_id: scene.hall_off

  # Pantry
  - id: light_hall_pantry_on
    alias: Pantry open
    description: Turn on the hall light closest to the pantry to get some extra pantry light
    trigger:
      - entity_id: binary_sensor.pantry_door
        platform: state
        to: "on"
    condition:
      - condition: state
        entity_id: binary_sensor.pantry_door
        state: "on"
    action:
      - if:
          - condition: state
            entity_id: input_select.home_mode
            state: Night
        then:
          - service: scene.turn_on
            entity_id: scene.pantry_night
        else:
          - service: scene.turn_on
            entity_id: scene.pantry_day

scene:
  - id: light_hall_100
    name: Hall 100%
    entities:
      light.hall_1:
        brightness: 255
        state: "on"
      light.hall_2:
        brightness: 255
        state: "on"
      light.hall_3:
        brightness: 255
        state: "on"

  - id: light_hall_75
    name: Hall 75%
    entities:
      light.hall_1:
        brightness: 192
        state: "on"
      light.hall_2:
        brightness: 192
        state: "on"
      light.hall_3:
        brightness: 192
        state: "on"

  - id: light_hall_50
    name: Hall 50%
    entities:
      light.hall_1:
        brightness: 127
        state: "on"
      light.hall_2:
        brightness: 127
        state: "on"
      light.hall_3:
        brightness: 127
        state: "on"

  - id: light_hall_25
    name: Hall 25%
    entities:
      light.hall_1:
        brightness: 16
        state: "on"
      light.hall_2:
        brightness: 64
        state: "on"
      light.hall_3:
        brightness: 16
        state: "on"

  - id: light_hall_off
    name: Hall off
    entities:
      light.hall_1:
        state: "off"
      light.hall_2:
        state: "off"
      light.hall_3:
        state: "off"

  - id: light_hall_night
    name: Hall night
    entities:
      light.hall_1:
        state: "off"
      light.hall_2:
        state: "on"
        brightness: 16
      light.hall_3:
        state: "off"

  - id: light_hall_low
    name: Hall low
    entities:
      light.hall_1:
        brightness: 32
        state: "on"
      light.hall_2:
        brightness: 32
        state: "on"
      light.hall_3:
        brightness: 32
        state: "on"

  - id: light_pantry_day
    name: Pantry day
    entities:
      light.hall_3:
        brightness: 255
        state: "on"

  - id: light_pantry_night
    name: Pantry night
    entities:
      light.hall_3:
        brightness: 128
        state: "on"
