---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   05/05/2021
#   @package        :   Office light automation
#   @description    :   Automates the WLED strip behind my desk
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################

automation:
  - id: light_office_wled_turn_on
    alias: Office - turn LEDs on
    description: Turn the lights behind the desk on when I turn on my computer(s)
    trigger:
      - entity_id: group.office_members   # computers/laptops that might be in the office
        platform: state
        to: home
      - entity_id: input_boolean.master_switch
        platform: state
        to: "on"
      - entity_id: binary_sensor.office_presence
        platform: state
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.master_switch
        state: "on"
      - condition: state
        entity_id: group.office_members
        state: home
    action:
      - service: select.select_option
        data:
          option: Desk
        target:
          entity_id: select.bureau_wled_preset


  - id: light_office_wled_turn_off
    alias: Office - turn LEDs off
    description: Turn the lights behind the desk off when I turn off my computer(s)
    trigger:
      - entity_id: group.office_members
        platform: state
        to: not_home
      - entity_id: input_boolean.master_switch
        platform: state
        to: "off"
      - entity_id: binary_sensor.office_presence
        platform: state
        to: "off"
        for: "00:10:00"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: group.office_members
            state: not_home
          - condition: state
            entity_id: binary_sensor.office_presence
            state: "off"
    action:
      - service: select.select_option
        data:
          option: "Off"
        target:
          entity_id: select.bureau_wled_preset
