---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   05/2021
#   @package        :   General hall light automation
#   @description    :   Motion, presence and sun based hall light automation
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################

automation:
  - id: light_hall_presence_day
    alias: Hall presence detected during day
    description: Increase hall brightness during the day when presence is detected
    trigger:
      - entity_id: binary_sensor.hall_presence
        platform: state
        to: "on"
      - entity_id: binary_sensor.pantry_presence
        platform: state
        to: "off"
      - entity_id: input_boolean.master_switch
        platform: state
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.master_switch
        state: "on"
      - condition: state
        entity_id: input_select.home_mode
        state: Day
      - condition: state
        entity_id: sensor.very_sunny
        state: "False"
      - condition: state
        entity_id: binary_sensor.hall_presence
        state: "on"
    action:
      - service: scene.turn_on
        entity_id: scene.hall_100

  - id: light_hall_presence_morning_and_evening
    alias: Hall presence detected during morning and evening
    description: Increase hall brightness during the morning and evening when presence is detected
    trigger:
      - entity_id: binary_sensor.hall_presence
        platform: state
        to: "on"
      - entity_id: binary_sensor.pantry_presence
        platform: state
        to: "off"
      - entity_id: input_boolean.master_switch
        platform: state
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.master_switch
        state: "on"
      - condition: state
        entity_id: binary_sensor.hall_presence
        state: "on"
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.home_mode
            state: Day
    action:
      - service: scene.turn_on
        entity_id: scene.hall_50


  - id: light_hall_presence_night
    alias: Hall presence detected during night
    description: Turn on a little light during the night when presence detected
    trigger:
      - entity_id: binary_sensor.hall_presence
        platform: state
        to: "on"
      - entity_id: binary_sensor.pantry_presence
        platform: state
        to: "off"
    condition:
      - condition: state
        entity_id: binary_sensor.hall_presence
        state: "on"
      - condition: state
        entity_id: input_boolean.master_switch
        state: "off"
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.home_mode
            state: Day
    action:
      - service: scene.turn_on
        entity_id: scene.hall_night


  ## SENSOR CLEAR ##
  - id: light_hall_clear_day
    alias: Hall no presence during day
    description: Keep a dim light on during the day when no presence is detected
    trigger:
      - entity_id: binary_sensor.hall_presence
        platform: state
        to: "off"
        for: "00:01:00"
      - entity_id: sensor.very_sunny
        platform: state
        to: "False"
      - entity_id: input_boolean.master_switch
        platform: state
        to: "on"
      - entity_id: binary_sensor.pantry_presence
        platform: state
        to: "off"
      - platform: state
        entity_id: input_select.home_mode
        to: Day
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state: Day
      - condition: state
        entity_id: binary_sensor.hall_presence
        state: "off"
      - condition: state
        entity_id: sensor.very_sunny
        state: "False"
      - condition: state
        entity_id: input_boolean.master_switch
        state: "on"
    action:
      - service: scene.turn_on
        entity_id: scene.hall_25
        data:
          transition: 3


  - id: light_hall_clear_evening
    alias: Hall no presence during the evening
    description: Keeps a dim light on during the evening when no motion is detected
    trigger:
      - entity_id: binary_sensor.hall_presence
        platform: state
        to: "off"
        for: "00:01:00"
      - entity_id: input_boolean.master_switch
        platform: state
        to: "on"
      - entity_id: binary_sensor.pantry_presence
        platform: state
        to: "off"
      - platform: state
        entity_id: input_select.home_mode
    condition:
      - condition: state
        entity_id: input_boolean.master_switch
        state: "on"
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.home_mode
            state: Day
      - condition: state
        entity_id: binary_sensor.hall_presence
        state: "off"
    action:
      - service: scene.turn_on
        entity_id: scene.hall_25
        data:
          transition: 3

  # This used to turn the hall lights off when it's sunny because the lights were of no much use,
  # but it kept confusing me because "off" could also have meant that
  # the master switch was turned off (or I forgot to turn it on in the morning)
  - id: light_hall_dimmed_very_sunny_day
    alias: Hall minimum brightness during sunny day
    description: Turn the lights to minimum brightness when it's sunny during the day
    trigger:
      - entity_id: binary_sensor.hall_presence
        platform: state
        to: "off"
        for: "00:01:00"
      - entity_id: input_boolean.master_switch
        platform: state
        to: "on"
      - entity_id: binary_sensor.pantry_presence
        platform: state
        to: "off"
      - entity_id: sensor.very_sunny
        platform: state
        to: "True"
    condition:
      - condition: state
        entity_id: sensor.very_sunny
        state: "True"
      - condition: state
        entity_id: input_boolean.master_switch
        state: "on"
      - condition: state
        entity_id: input_select.home_mode
        state: Day
    action:
      - service: scene.turn_on
        entity_id: scene.hall_10


  - id: light_hall_off_night
    alias: Hall off at night
    description: Turn the lights off when it's night
    trigger:
      - entity_id: binary_sensor.hall_presence
        platform: state
        to: "off"
      - entity_id: binary_sensor.pantry_presence
        platform: state
        to: "off"
      - entity_id: input_boolean.master_switch
        platform: state
        to: "off"
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state: Night
      - condition: state
        entity_id: binary_sensor.hall_presence
        state: "off"
      - condition: state
        entity_id: input_boolean.master_switch
        state: "off"
    action:
      - service: scene.turn_on
        entity_id: scene.hall_off

  # Pantry
  - id: light_hall_pantry_on_day
    alias: Pantry open day
    description: Turn on the hall light closest to the pantry to get some extra pantry light
    trigger:
      - entity_id: binary_sensor.pantry_presence
        platform: state
        to: "on"
    condition:
      - condition: state
        entity_id: binary_sensor.pantry_presence
        state: "on"
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.home_mode
            state: Night
    action:
      - service: light.turn_on
        data:
          brightness: 255
          entity_id:
            - light.hall_3

  - id: light_hall_pantry_on_night
    alias: Pantry open night
    description: Turn on the hall light closest to the pantry to get some extra pantry light (but less bright because it's night time)
    trigger:
      - entity_id: binary_sensor.pantry_presence
        platform: state
        to: "on"
    condition:
      - condition: state
        entity_id: binary_sensor.pantry_presence
        state: "on"
      - condition: state
        entity_id: input_select.home_mode
        state: Night
    action:
      - service: light.turn_on
        data:
          brightness: 96
          entity_id:
            - light.hall_3

scene:
  - id: light_hall_100
    name: Hall 100%
    entities:
      light.hall_lights:
        brightness: 255
        state: "on"

  - id: light_hall_75
    name: Hall 75%
    entities:
      light.hall_lights:
        brightness: 192
        state: "on"

  - id: light_hall_50
    name: Hall 50%
    entities:
      light.hall_lights:
        brightness: 128
        state: "on"

  - id: light_hall_25
    name: Hall 25%
    entities:
      light.hall_1:
        brightness: 16
        state: "on"
      light.hall_2:
        brightness: 64
        state: "on"
      light.hall_3:
        brightness: 16
        state: "on"

  - id: light_hall_off
    name: Hall off
    entities:
      light.hall_lights:
        state: "off"

  - id: light_hall_night
    name: Hall night
    entities:
      light.hall_1:
        state: "off"
      light.hall_2:
        state: "on"
        brightness: 16
      light.hall_3:
        state: "off"

  - id: light_hall_low
    name: Hall low
    entities:
      light.hall_lights:
        brightness: 16
        state: "on"
