---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   05/05/2021
#   @package        :   Office light automation
#   @description    :   Automates the WLED strip behind my desk
#   @url            :   https://codeberg.org/PW999/home-assistant-config/
###############################################################################

automation:
  - id: light_office_wled_turn_on
    alias: Office - turn LEDs on
    description: Turn the lights behind the desk on when I turn on my computer(s)
    triggers:
      - entity_id: group.office_members # computers/laptops that might be in the office
        trigger: state
        to: home
      - entity_id: input_boolean.master_switch
        trigger: state
        to: "on"
      - entity_id: binary_sensor.office_presence
        trigger: state
        to: "on"
      - entity_id: sensor.pwmanjaro_cpu_usage
        trigger: state
        from: "unavailable"
      - entity_id: sensor.pwzenbookux303_cpuload
        trigger: state
        from: "unavailable"
    conditions:
      - condition: state
        entity_id: input_boolean.master_switch
        state: "on"
      - condition: or
        conditions:
          - condition: state
            entity_id: group.office_members
            state: home
          - condition: not
            conditions:
              - condition: state
                entity_id: sensor.pwmanjaro_cpu_usage
                state: "unavailable"
          - condition: not
            conditions:
              - condition: state
                entity_id: sensor.pwzenbookux303_cpuload
                state: "unavailable"
    actions:
      - action: light.turn_on
        target:
          entity_id: light.bureau_wled_master

  - id: light_office_wled_turn_off
    alias: Office - turn LEDs off
    description: Turn the lights behind the desk off when I turn off my computer(s)
    triggers:
      - entity_id: group.office_members
        trigger: state
        to: not_home
      - entity_id: input_boolean.master_switch
        trigger: state
        to: "off"
      - entity_id: binary_sensor.office_presence
        trigger: state
        to: "off"
        for: "00:10:00"
      - entity_id: sensor.pwmanjaro_cpu_usage
        trigger: state
        to: "unavailable"
        for: "00:00:10"
      - entity_id: sensor.pwzenbookux303_cpuload
        trigger: state
        to: "unavailable"
        for: "00:00:10"
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: group.office_members
            state: not_home
          - condition: state
            entity_id: binary_sensor.office_presence
            state: "off"
          - condition: and
            conditions:
              - condition: state
                entity_id: sensor.pwmanjaro_cpu_usage
                state: "unavailable"
              - condition: state
                entity_id: sensor.pwzenbookux303_cpuload
                state: "unavailable"
    actions:
      - action: light.turn_off
        target:
          entity_id: light.bureau_wled_master

  - id: light_office_ceiling_turn_on
    alias: Office - Turn ceiling WLED on
    description: Turn on the LED strip pointing at the ceiling
    triggers:
      - entity_id: input_boolean.master_switch
        trigger: state
        to: "on"
      - entity_id: binary_sensor.office_presence
        trigger: state
        to: "on"
      - entity_id: input_select.home_mode
        trigger: state
    conditions:
      - condition: state
        entity_id: input_boolean.master_switch
        state: "on"
      - condition: state
        entity_id: binary_sensor.office_presence
        state: "on"
      - condition: state
        entity_id: input_select.home_mode
        state:
          - Morning
          - Evening
          - Night
    actions:
      - action: light.turn_on
        data:
          brightness_pct: 100
          effect: Pixels
          rgb_color:
            - 255
            - 218
            - 153
        target:
          entity_id: light.office_ceiling
      - action: select.select_option
        data:
          option: "* Color Gradient"
        target:
          entity_id: select.office_ceiling_color_palette

  - id: light_office_ceiling_turn_off
    alias: Office - Turn ceiling WLED off
    description: Turn off the LED strip pointing at the ceiling
    triggers:
      - entity_id: input_boolean.master_switch
        trigger: state
        to: "off"
      - entity_id: binary_sensor.office_presence
        trigger: state
        to: "off"
        for: "00:07:00"
      - entity_id: input_select.home_mode
        trigger: state
        to: "Day"
    actions:
      - action: light.turn_off
        target:
          entity_id: light.office_ceiling
