---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   01/2022
#   @package        :   General Living room light automation
#   @description    :   Contains living room light
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################

automation:
  - id: light_living_room_evening_turn_on
    alias: Living room - turn on lights in the evening
    description: Turn on the living room lights in the evening based on sunset
    trigger:
      - entity_id: input_select.home_mode
        platform: state
        to: Evening
      - entity_id: input_select.home_mode
        platform: state
        to: Morning
      - entity_id: input_boolean.master_switch
        platform: state
        from: "off"
        to: "on"
      - entity_id: binary_sensor.living_room_presence
        platform: state
        to: "on"
      - entity_id: media_player.fire_tv_10_0_1_142  # immediately switch to movie mode
        platform: state
        to: "playing"
      - entity_id: media_player.fire_tv_10_0_1_142
        platform: state
        from: "playing"
        for: "00:02:00"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_select.home_mode
            state: Evening
          - condition: state
            entity_id: input_select.home_mode
            state: Morning
      - condition: state
        entity_id: input_boolean.master_switch
        state: "on"
    action:
      - if:
          - condition: state
            entity_id: media_player.fire_tv_10_0_1_142
            state: "playing"
          - condition: not
            conditions:
              - condition: state
                entity_id: media_player.fire_tv_10_0_1_142
                state: "org.polymorphicshade.newpipe"
                attribute: "source"
              - condition: state
                entity_id: media_player.fire_tv_10_0_1_142
                state: "Spotify"
                attribute: "source"
        then:
          - service: scene.turn_on
            entity_id: scene.living_room_movie
            data:
              transition: 2
        # The `else` is fully optional and can be omitted
        else:
          - service: scene.turn_on
            entity_id: scene.living_room_evening
            data:
              transition: 2


  - id: light_living_room_off_no_presence
    alias: Living room - turn off WLED strips if no presence detected
    description: Turn of power hungry WLED strips when I am not in the living
    trigger:
      - entity_id: binary_sensor.living_room_presence
        platform: state
        to: "off"
        for: "00:25:00"
      - entity_id: light.living_room_tv # handles the case where the lights go on but I'm not in the living for the next couple of hours
        platform: state
        to: "on"
        for: "00:10:00"
      - platform: state
        entity_id: media_player.fire_tv_10_0_1_142
        from: "playing"
        for: "00:25:00"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_select.home_mode
            state: Evening
          - condition: state
            entity_id: input_select.home_mode
            state: Night
          - condition: state
            entity_id: input_select.home_mode
            state: Morning
      - condition: state # for the tv light trigger
        entity_id: binary_sensor.living_room_presence
        state: "off"
        for: "00:10:00"
      - condition: state
        entity_id: input_boolean.master_switch
        state: "on"
      - condition: not
        conditions:
          - alias: "Do not turn off lights when I'm watching anything on TV"
            condition: state
            entity_id: media_player.fire_tv_10_0_1_142
            state: "playing"
    action:
      service: scene.apply
      data:
        transition: 4
        entities:
          light.front_window:
            state: "off"
          light.living_room_tv:
            state: "off"

  - id: light_living_room_morning_turn_off
    alias: Living room - turn off ligts in the morning
    description: Turn off the living room lights in the morning
    trigger:
      - entity_id: input_select.home_mode
        platform: state
        to: Day
    condition:
      - condition: state
        entity_id: input_boolean.master_switch
        state: "on"
      - condition: state
        entity_id: input_select.home_mode
        state: Day
    action:
      - service: scene.turn_on
        entity_id: scene.living_room_off
        data:
          transition: 3

  - id: light_living_room_dimm_lights
    alias: Living room - dimm the lights later in the evening
    description: Slowly dimm the living room lights at night
    trigger:
      - entity_id: input_select.home_mode
        platform: state
        to: Night
      - entity_id: input_boolean.master_switch
        platform: state
        from: "off"
        to: "on"
      - entity_id: binary_sensor.living_room_presence
        platform: state
        to: "on"
    condition:
      - condition: or
        conditions:
          - alias: Always trigger when master switch is the trigger
            condition: template
            value_template: "{{ trigger.entity_id == 'input_boolean.master_switch' }}"
          - condition: and
            conditions:
              - alias: Check if the trigger is the house mode
                condition: template
                value_template: "{{ trigger.entity_id == 'input_select.home_mode' }}"
              - alias: Check if the lights are still on (should be on because of Evening mode)
                condition: state
                entity_id: light.living_room_big
                state: "on"
          - condition: and
            conditions:
              - alias: Check if the trigger is the motion sensor
                condition: template
                value_template: "{{ trigger.entity_id == 'binary_sensor.living_room_presence' }}"
              - alias: Check if the lights are still on
                condition: state
                entity_id: light.living_room_big
                state: "on"
      - condition: state
        entity_id: input_boolean.master_switch
        state: "on"
      - condition: state
        entity_id: input_select.home_mode
        state: Night
    action:
      - service: scene.turn_on
        entity_id: scene.living_room_evening_dimmed
        data:
          transition: 60

scene:
  - id: light_living_room_scene_evening
    name: Living Room Evening
    entities:
      light.front_window:
        intensity: 97
        speed: 35
        state: "on"
        brightness: 192
        effect: Candle Multi
        rgb_color:
          - 255
          - 0
          - 0
      light.living_room_tv:
        intensity: 166
        speed: 25
        state: "on"
        brightness: 192
        effect: Palette
      light.living_room_big:
        color_temp: 320
        brightness: 220
        state: "on"
      light.living_room_small:
        color_temp: 320
        brightness: 192
        state: "on"
      switch.gosund_sp112_4_usb:
        state: "on"
  - id: light_living_room_scene_movie
    name: Living Room Movie
    entities:
      light.front_window:
        intensity: 97
        speed: 35
        state: "on"
        brightness: 192
        effect: Candle Multi
        rgb_color:
          - 255
          - 0
          - 0
      light.living_room_tv:
        intensity: 166
        speed: 25
        state: "on"
        brightness: 192
        effect: Palette
      light.living_room_big:
        color_temp: 320
        brightness: 100
        state: "on"
      light.living_room_small:
        color_temp: 320
        brightness: 16
        state: "on"
      switch.gosund_sp112_4_usb:
        state: "on"
  - id: light_living_room_scene_off
    name: Living Room off
    entities:
      light.front_window:
        state: "off"
      light.living_room_tv:
        state: "off"
      light.living_room_big:
        state: "on"
        brightness: 0
        color_temp: 320
      light.living_room_small:
        state: "on"
        brightness: 0
        color_temp: 320
      switch.gosund_sp112_4_usb:
        state: "off"
  - id: light_living_room_scene_dimmed
    name: Living Room Evening Dimmed
    entities:
      light.front_window:
        intensity: 97
        speed: 35
        state: "on"
        brightness: 128
        effect: Candle Multi
        rgb_color:
          - 255
          - 0
          - 0
      light.living_room_tv:
        intensity: 166
        speed: 25
        state: "on"
        brightness: 128
        effect: Palette
      light.living_room_big:
        color_temp: 370
        brightness: 96
        state: "on"
      light.living_room_small:
        color_temp: 370
        brightness: 64
        state: "on"
      switch.gosund_sp112_4_usb:
        state: "on"
