---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   01/2022
#   @package        :   General toilet light automation
#   @description    :   Way to complex toilet light scheme for my toilet
#   @url            :   https://codeberg.org/PW999/home-assistant-config/
###############################################################################

automation:
  - id: light_toilet_on
    alias: Toilet light on
    description: Turns the toilet light on when motion is detected
    triggers:
      - entity_id: binary_sensor.toilet_presence
        trigger: state
        to: "on"
    actions:
      - action: light.turn_on
        data_template:
          brightness: "{{ [16, (255 * ( cos(0.12* ( 13 - now().hour)) - 0.05 ) / 0.8)] | max | round(0) }}"  # https://www.desmos.com/calculator
          transition: 1
          entity_id:
            - light.toilet_light

  - id: light_toilet_off
    alias: Toilet light off
    description: Turns the toilet light off when motion is not detected for 5 min
    triggers:
      - entity_id: binary_sensor.toilet_presence
        trigger: state
        to: "off"
        for: "00:05:00"
    actions:
      - action: light.turn_off
        data:
          transition: 4
          entity_id:
            - light.toilet_light
