---
# ##############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   08/2022
#   @package        :   Work from home calendar package
#   @description    :   Automation for work from home stuff
#   @url            :   https://github.com/PW999/home-assistant-config/
# ##############################################################################
calendar:
- platform: ics_calendar
  calendars:
    - name: "Calendar - Work from home"
      url: !secret outlook_work_url
      include_all_day: True
      download_interval: 240
      exclude: "['/.*/']"
      include: "['WFH']"

input_boolean:
  work_from_home:
    name: Work from home
    icon: mdi:home-city

# So, full day events don't seems to trigger the calendar automation events ...
# That's why I'm just using simple state triggers here
# It seems a bit stupid though to replicate the value of a calendar in a boolean
# but it decouples the calendar from the rest of the system which is nice I guess
automation:
  - id: calendar_wfh_start_work_from_home
    alias: Calendar WFH - Start work from home
    trigger:
      - platform: state
        entity_id: calendar.calendar_work_from_home
        to: "on"
    action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.work_from_home

  - id: calendar_wfh_end_work_from_home
    alias: Calendar WFH - End work from home
    trigger:
      - platform: state
        entity_id: calendar.calendar_work_from_home
        to: "off"
    action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.work_from_home