---
# ##############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   08/2022
#   @package        :   Vacation package
#   @description    :   Combine the workday sensor with my vacation calendar
#   @url            :   https://github.com/PW999/home-assistant-config/
# ##############################################################################

calendar:
  - platform: ics_calendar
    calendars:
      - name: "Calendar - Day off"
        url: !secret outlook_work_url
        include_all_day: True
        download_interval: 240
        exclude: "['/.*/']"
        include: "['Verlof', 'Vakantie']"

binary_sensor:
  - platform: workday
    country: BE

input_boolean:
  work_day:
    name: Work day
    icon: mdi:briefcase
  day_off:
    name: Day off
    icon: mdi:briefcase

# So, full day events don't seems to trigger the calendar automation events ...
# That's why I'm just using simple state triggers here
# It seems a bit stupid though to replicate the value of a calendar in a boolean
# but it decouples the calendar from the rest of the system which is nice I guess
automation:
  - id: calendar_vacation_turn_on_day_off
    alias: Calendar Vacation - Turn on day off
    trigger:
      - platform: state
        entity_id: calendar.calendar_day_off
        to: "on"
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.day_off

  - id: calendar_vacation_turn_off_day_off
    alias: Calendar Vacation - Turn off day off
    trigger:
      - platform: state
        entity_id: calendar.calendar_day_off
        to: "off"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.day_off

  - id: calendar_vacation_toggle_work_day
    alias: Calendar vacation - Toggle work day
    trigger:
      - platform: state
        entity_id: input_boolean.day_off
      - platform: state
        entity_id: binary_sensor.workday_sensor
    action:
      - if:
          - condition: or
            conditions:
              - condition: state
                entity_id: input_boolean.day_off
                state: "on"
              - condition: state
                entity_id: binary_sensor.workday_sensor
                state: "off"
        then:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.work_day
        else:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.work_day
