---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   05/05/2021
#   @package        :   Morning notification
#   @description    :   Send me an update every morning
#   @url            :   https://codeberg.org/PW999/home-assistant-config/
###############################################################################

automation:
  - id: morning_notification_workday
    alias: Notification - Morning notification on workday
    description: Send morning updates to my smartphone on a workday
    mode: single
    triggers:
      - trigger: time
        at: "06:50:00"
    conditions:
      - condition: state
        entity_id: input_select.presence_mode
        state: "Workday"
    actions:
      - action: notify.mobile_app_pwxperia10iv
        data:
          data:
            actions:
              - action: TURN_MASTER_SWITCH_ON
                title: Turn master on
          message: >
            Goodmorning, it's a {{ states('weather.pw_casa') }} {{ state_attr('weather.pw_casa', 'temperature') }}°C.<br />
            Travel time is {{ states('sensor.to_work') }} {{ state_attr('sensor.to_work', 'unit_of_measurement') }}<br />
            Today will be {{ state_attr('sensor.weather_tomorrow', 'forecast').condition }} at {{ state_attr('sensor.weather_tomorrow', 'forecast').templow }}
            - {{ state_attr('sensor.weather_tomorrow', 'forecast').temperature }}°C with {{ state_attr('sensor.weather_tomorrow', 'forecast').precipitation }}mm rain.
          title: Good morning
      - delay: 600

  - id: morning_notification_non_workday
    alias: Notification - Morning notification on non-workdays
    description: Send morning updates to my smartphone on a non-working day
    mode: single
    triggers:
      - trigger: time
        at: "08:15:00"
    conditions:
      - condition: state
        entity_id: input_select.presence_mode
        state: "Normal"
    actions:
      - action: notify.mobile_app_pwxperia10iv
        data:
          data:
            actions:
              - action: TURN_MASTER_SWITCH_ON
                title: Turn master on
          message: >
            Goodmorning, it's a {{ states('weather.pw_casa') }} {{ state_attr('weather.pw_casa', 'temperature') }}°C.<br />
            Today will be {{ state_attr('sensor.weather_tomorrow', 'forecast').condition }} at {{ state_attr('sensor.weather_tomorrow', 'forecast').templow }}
            - {{ state_attr('sensor.weather_tomorrow', 'forecast').temperature }}°C with {{ state_attr('sensor.weather_tomorrow', 'forecast').precipitation }}mm rain.
          title: Good morning
      - delay: 600

  - id: morning_notification_work_from_home
    alias: Notification - Morning notification when working from home
    description: Send morning updates to my smartphone when working from home
    mode: single
    triggers:
      - trigger: time
        at: "07:55:00"
    conditions:
      - condition: state
        entity_id: input_select.presence_mode
        state: "WFH"
    actions:
      - action: notify.mobile_app_pwxperia10iv
        data:
          data:
            actions:
              - action: TURN_MASTER_SWITCH_ON
                title: Turn master on
          message: >
            Goodmorning, it's a {{ states('weather.pw_casa') }} {{ state_attr('weather.pw_casa', 'temperature') }}°C.<br />
            Today will be {{ state_attr('sensor.weather_tomorrow', 'forecast').condition }} at {{ state_attr('sensor.weather_tomorrow', 'forecast').templow }}
            - {{ state_attr('sensor.weather_tomorrow', 'forecast').temperature }}°C with {{ state_attr('sensor.weather_tomorrow', 'forecast').precipitation }}mm rain.
          title: Good morning
      - delay: 600
