---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   05/05/2021
#   @package        :   Morning notification
#   @description    :   Send me an update every morning
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################


automation:
  - id: morning_notification_workday
    alias: Notification - Morning notification on workday
    description: Send morning updates to my smartphone on a workday
    mode: single
    trigger:
      - platform: time
        at: "07:02:00"
    condition:
      - condition: state
        entity_id: input_boolean.work_day
        state: "on"
      - condition: state
        entity_id: input_boolean.work_from_home
        state: "off"
      - condition: state
        entity_id: input_boolean.vacation
        state: "off"
    action:
      - service: notify.mobile_app_mi_9t
        data:
          data:
            actions:
              - action: TURN_MASTER_SWITCH_ON
                title: Turn master on
          message: >
            Goodmorning, it's a {{ states('weather.pw_casa') }} {{ state_attr('weather.pw_casa', 'temperature') }}°C.<br />
            Travel time is {{ states('sensor.to_work') }} {{ state_attr('sensor.to_work', 'unit_of_measurement') }}<br />
            Today will be {{ states('input_text.weather_forecast') }} at {{ states('input_number.forecast_min_temp') | trim }}
            - {{ states('input_number.forecast_temp') | trim }}°C with {{ states('input_number.forecast_precip') | trim }}mm rain.
          title: Good morning
      - delay: 600

  - id: morning_notification_non_workday
    alias: Notification - Morning notification on non-workdays
    description: Send morning updates to my smartphone on a non-working day
    mode: single
    trigger:
      - platform: time
        at: '08:30:00'
    condition:
      - condition: state
        entity_id: input_boolean.work_day
        state: "off"
      - condition: state
        entity_id: input_boolean.work_from_home
        state: "off"
      - condition: state
        entity_id: input_boolean.vacation
        state: "off"
    action:
      - service: notify.mobile_app_mi_9t
        data:
          data:
            actions:
              - action: TURN_MASTER_SWITCH_ON
                title: Turn master on
          message: >
            Goodmorning, it's a {{ states('weather.pw_casa') }} {{ state_attr('weather.pw_casa', 'temperature') }}°C.<br />
            Today will be {{ states('input_text.weather_forecast') }} at {{ states('input_number.forecast_min_temp') | trim }}
             - {{ states('input_number.forecast_temp') | trim }}°C with {{ states('input_number.forecast_precip') | trim }}mm rain.
          title: Good morning
      - delay: 600

  - id: morning_notification_work_from_home
    alias: Notification - Morning notification when working from home
    description: Send morning updates to my smartphone when working from home
    mode: single
    trigger:
      - platform: time
        at: '07:55:00'
    condition:
      - condition: state
        entity_id: input_boolean.work_day
        state: "on"
      - condition: state
        entity_id: input_boolean.work_from_home
        state: "on"
      - condition: state
        entity_id: input_boolean.vacation
        state: "off"
    action:
      - service: notify.mobile_app_mi_9t
        data:
          data:
            actions:
              - action: TURN_MASTER_SWITCH_ON
                title: Turn master on
          message: >
            Goodmorning, it's a {{ states('weather.pw_casa') }} {{ state_attr('weather.pw_casa', 'temperature') }}°C.<br />
            Today will be {{ states('input_text.weather_forecast') }} at {{ states('input_number.forecast_min_temp') | trim }}
             - {{ states('input_number.forecast_temp') | trim }}°C with {{ states('input_number.forecast_precip') | trim }}mm rain.
          title: Good morning
      - delay: 600
