---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   17/04/2022
#   @package        :   Capacity tarif notification
#   @description    :   When over 2.5kWh for 15 min, we have to pay more
#   @url            :   https://codeberg.org/PW999/home-assistant-config/
###############################################################################

automation:
  - id: notification_capaciteit_tarief
    alias: Notification - Capaciteit tarief
    description: Send a notification when risking to use more than the 'basic' 2.5kWh
    mode: single
    triggers:
        # retrigger often, the template as trigger will be too expensive to run
      - trigger: numeric_state
        entity_id: sensor.electricity_meter_current_average_demand
        above: 1.80
      - trigger: numeric_state
        entity_id: sensor.electricity_meter_current_average_demand
        above: 1.90
      - trigger: numeric_state
        entity_id: sensor.electricity_meter_current_average_demand
        above: 2.0
      - trigger: numeric_state
        entity_id: sensor.electricity_meter_current_average_demand
        above: 2.1
      - trigger: numeric_state
        entity_id: sensor.electricity_meter_current_average_demand
        above: 2.2
      - trigger: numeric_state
        entity_id: sensor.electricity_meter_current_average_demand
        above: 2.3
    conditions:
      - condition: or
        conditions:
            # div by zero but let's just assume we won't even hit 1kWh avg demand at start of window
          - alias: "If the continue load will result in > 2.5kWh"
            condition: template
            value_template: "(float(states('sensor.electricity_meter_current_average_demand')) / float(now().strftime('%M')) * 15) > 2.45"
          - alias: "Always notify if it's very high"
            condition: numeric_state
            entity_id: sensor.electricity_meter_current_average_demand
            above: 2.29
    actions:
      - action: notify.mobile_app_pwxperia10iv
        data:
          message: |
            Average power consumption is {{ states('sensor.electricity_meter_current_average_demand') }}.
          title: Capaciteits tarief
      - delay: 300 # cheap trick to only send it once every 5 min
