---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   01/2022
#   @package        :   Homematic package
#   @description    :   Integrates local running RaspberryMatic and regulates thermostat
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################

homematic:
  interfaces:
    ip:
      host: 192.168.0.16
      port: 2010
      resolvenames: json
      username: !secret homematic_user
      password: !secret homematic_password

binary_sensor:
  - platform: template
    sensors:
      homematic_up:
        friendly_name: Homematic is sending updates
        availability_template: >-
          {{
               not (
                  is_state('sensor.hmip_000a1709af6337_valve', 'unavailable')
                  or is_state('sensor.hmip_000a1709af6337_valve', 'unknown')
              )
          }}
        value_template: >-
          {{ as_timestamp(now()) - ( [as_timestamp(states.sensor.hmip_000a1709af6337_valve.last_changed), as_timestamp(states.sensor.hmip_000a1709af6337_rssi.last_changed)]  | max ) < 7200 }}

sensor:
  - platform: template
    sensors:
      hmip_000a1709af6337_valve:
        unique_id: hmip_000a1709af6337_valve
        friendly_name: 000a1709af6337 valve
        unit_of_measurement: "%"
        availability_template: "{{ not is_state('climate.000a1709af6337', 'unavailable')  }}"
        value_template: "{{ state_attr('climate.000a1709af6337', 'level') * 100 | round(0) | int }}"
      hmip_000a1709af6337_rssi:
        unique_id: hmip_000a1709af6337_rssi
        friendly_name: 000a1709af6337 rssi
        device_class: signal_strength
        unit_of_measurement: "dBm"
        availability_template: "{{ not is_state('climate.000a1709af6337', 'unavailable')  }}"
        value_template: "{{ state_attr('climate.000a1709af6337', 'rssi_device') }}"
      hmip_00201d89a8ac5e_valve:
        unique_id: hmip_00201d89a8ac5e_valve
        friendly_name: 00201d89a8ac5e valve
        unit_of_measurement: "%"
        availability_template: "{{ not is_state('climate.00201d89a8ac5e', 'unavailable')  }}"
        value_template: "{{ state_attr('climate.00201d89a8ac5e', 'level') * 100 | round(0) | int }}"
      hmip_00201d89a8ac5e_rssi:
        unique_id: hmip_00201d89a8ac5e_rssi
        friendly_name: 00201d89a8ac5e rssi
        device_class: signal_strength
        unit_of_measurement: "dBm"
        availability_template: "{{ not is_state('climate.00201d89a8ac5e', 'unavailable')  }}"
        value_template: "{{ state_attr('climate.00201d89a8ac5e', 'rssi_device') }}"

automation:
  - id: climate_homematic_auto_reconnect
    alias: Heating - Homematic Reconnect
    trigger:
      platform: state
      entity_id: binary_sensor.homematic_up
      to: "off"
    action:
      service: homematic.reconnect
