---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   12/2023
#   @package        :   Disables/Enables Frigate and Reolink detection
#   @description    :   Frigate consumes a lot of CPU, don't when I'm at home. Also disable Reolink detection so it doesn't record my every move to SD.
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################

automation:
  - id: camera_enable_detection
    alias: Camera - Enable camera detection
    mode: single
    description: Enables camera detection when I'm not at home (or asleep)
    trigger:
      - platform: state
        entity_id: input_boolean.master_switch
        to: "off"
      - platform: state
        entity_id: input_boolean.vacation
        to: "on"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.vacation
            state: "on"
          - condition: state
            entity_id: input_boolean.master_switch
            state: "off"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.reolink_rlc510wa_motion
      - service: switch.turn_on
        target:
          entity_id: switch.reolink_rlc520a_motion
      - service: switch.turn_on
        target:
          entity_id: switch.r2m_1_onvif_motion
      - service: switch.turn_on
        target:
          entity_id: switch.reolink_rlc510wa_detect
      - service: switch.turn_on
        target:
          entity_id: switch.reolink_rlc520a_detect
      - service: switch.turn_on
        target:
          entity_id: switch.r2m_1_onvif_detect
      - service: number.set_value
        target:
          entity_id: number.rlc_510wa_motion_sensitivity
        data:
          value: 22
      - service: number.set_value
        target:
          entity_id: number.rlc_520a_motion_sensitivity
        data:
          value: 22    

  - id: camera_disable_detection
    alias: Camera - Disable detection
    mode: single
    description: Disable camera detection when I'm at home
    trigger:
      - platform: state
        entity_id: input_boolean.master_switch
        to: "on"
      - platform: state
        entity_id: input_boolean.vacation
        to: "off"
    condition:
        - condition: state
          entity_id: input_boolean.vacation
          state: "off"
        - condition: state
          entity_id: input_boolean.master_switch
          state: "on"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.reolink_rlc510wa_detect
      - service: switch.turn_off
        target:
          entity_id: switch.reolink_rlc520a_detect
      - service: switch.turn_off
        target:
          entity_id: switch.r2m_1_onvif_detect
      - service: switch.turn_off
        target:
          entity_id: switch.reolink_rlc510wa_motion
      - service: switch.turn_off
        target:
          entity_id: switch.reolink_rlc520a_motion
      - service: switch.turn_off
        target:
          entity_id: switch.r2m_1_onvif_motion
      - service: number.set_value
        target:
          entity_id: number.rlc_510wa_motion_sensitivity
        data:
          value: 1
      - service: number.set_value
        target:
          entity_id: number.rlc_520a_motion_sensitivity
        data:
          value: 1