---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   12/2023
#   @package        :   Disables/Enables Frigate and Reolink detection
#   @description    :   Frigate consumes a lot of CPU, don't when I'm at home. Also disable Reolink detection so it doesn't record my every move to SD.
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################

automation:
  - id: camera_enable_detection
    alias: Camera - Enable camera detection
    mode: single
    description: Enables camera detection when I'm not at home (or asleep), or if on vacation
    triggers:
      - trigger: homeassistant
        event: start
      - trigger: state
        entity_id: input_boolean.master_switch
        to: "off"
      - trigger: state
        entity_id: input_boolean.vacation
        to: "on"
    conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.vacation
            state: "on"
          - condition: state
            entity_id: input_boolean.master_switch
            state: "off"
    action:
      - action: hassio.addon_start
        data:
          addon: ccab4aaf_frigate
      - action: number.set_value
        target:
          entity_id: number.rlc_510wa_motion_sensitivity
        data:
          value: 15
      - action: number.set_value
        target:
          entity_id: number.rlc_520a_motion_sensitivity
        data:
          value: 15
      - action: number.set_value
        target:
          entity_id: number.rlc_510wa_ai_person_sensitivity
        data:
          value: 50
      - action: number.set_value
        target:
          entity_id: number.rlc_520a_ai_person_sensitivity
        data:
          value: 50    

  - id: camera_disable_detection
    alias: Camera - Disable detection
    mode: single
    description: Disable camera detection when I'm at home
    triggers:
      - trigger: state
        entity_id: input_boolean.master_switch
        to: "on"
      - trigger: state
        entity_id: input_boolean.vacation
        to: "off"
    conditions:
        - condition: state
          entity_id: input_boolean.vacation
          state: "off"
        - condition: state
          entity_id: input_boolean.master_switch
          state: "on"
    actions:
      - action: hassio.addon_stop
        data:
          addon: ccab4aaf_frigate
      - action: number.set_value
        target:
          entity_id: number.rlc_510wa_motion_sensitivity
        data:
          value: 1
      - action: number.set_value
        target:
          entity_id: number.rlc_520a_motion_sensitivity
        data:
          value: 1
      - action: number.set_value
        target:
          entity_id: number.rlc_510wa_ai_person_sensitivity
        data:
          value: 1
      - action: number.set_value
        target:
          entity_id: number.rlc_520a_ai_person_sensitivity
        data:
          value: 1

  - id: camera_load_frigate_integration
    alias: Camera - Load frigate integration
    mode: single
    description: After startup, temporarily launch frigate so HA can load the ingration
    triggers:
      - trigger: homeassistant
        event: start
    conditions:
        - condition: state
          entity_id: input_boolean.vacation
          state: "off"
        - condition: state
          entity_id: input_boolean.master_switch
          state: "on"
    actions:
      - action: hassio.addon_start
        data:
          addon: ccab4aaf_frigate
      - delay: 600
      - action: hassio.addon_stop
        data:
          addon: ccab4aaf_frigate