---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   04/2021
#   @package        :   Foscam camera integration
#   @description    :   Foscam motion sensor control
#   @url            :   https://github.com/PW999/home-assistant-config/
#   @credit         :   TODO
###############################################################################

# TODO:
# [ ] Site source (find it first, should have noted it when I used it)

# Command lines used in this template to get data from the camera using the XML API
# I do not have motion detection enabled in all area's
# foscam_r2m_one_motion_on_url: 'curl -k --tls-max 1.2 "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=1&snapInterval=3&sensitivity=3&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=960&area1=960&area2=960&area3=960&area4=960&area5=960&area6=992&area7=1016&area8=1020&area9=1023&linkage=12&usr=ADMIN&pwd=PASSWD"'
# foscam_r2m_one_motion_off_url: 'curl -k --tls-max 1.2 \
#  "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=0&usr=ADMIN&pwd=PASSWD"'
#
# foscam_r2m_one_motion_state_url:  'curl -k --silent --tls-max 1.2 \
#  "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=getMotionDetectConfig&usr=ADMIN&pwd=PASSWD" | grep "isEnable" | cut -b 15'
#
# foscam_r2m_one_motion_detected_url: curl -k --silent --tls-max 1.2 \
#  "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=getDevState&usr=ADMIN&pwd=PASSWD" | grep "motionDetectAlarm" | cut -b 24
#
# foscam_r2m_one_infrared_off_url: 'curl -k --tls-max 1.2 "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=closeInfraLed&usr=ADMIN&pwd=PASSWD"'
# foscam_r2m_one_infrared_on_url: 'curl -k --tls-max 1.2 "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=openInfraLed&usr=ADMIN&pwd=PASSWD"'
# foscam_r2m_one_infrared_state_url: 'curl -k --silent --tls-max 1.2 "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=getDevState&usr=ADMIN&pwd=PASSWD" | \
#  grep "infraLedState" | cut -b 20'
#
# Gets the log events and translates the event id's to something more human readable
# foscam_r2m_one_log_0: curl -s -k --tls-max 1.2 "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=getLog&usr=ADMIN&pwd=PASSWD" | sed 's/%2B/ /g' | grep log0 | sed 's/<\/*log[0-9]>//g' | \
#  awk '{split($0,a); b = strftime("%d/%m/%Y %H:%M:%S", a[1], 1); c = a[4]; if (c == "1") { c="Motion"}; if (c == "3") { c = "Login " a[2] }; if (c == "4") { c="Logout " a[2]}; print b " " c; }'

homeassistant:
  customize:
    switch.foscam_r2m_one_motion:
      icon: mdi:cctv
      friendly_name: Foscam R2M-1 Motion Sensor

command_line:
  switch:
    name: foscam_r2m_one_motion
    command_on: !secret foscam_r2m_one_motion_on_url
    command_off: !secret foscam_r2m_one_motion_off_url
    command_state: !secret foscam_r2m_one_motion_state_url
    value_template: '{{ value == "1" }}'

automation:
  - id: camera_front_door_motion_detection_disable
    alias: Camera - Disable motion detection
    description: Disable the camera surveillance
    initial_state: false # Always keep motion detection enabled, even though it's crappy
    trigger:
      - platform: state
        entity_id: input_boolean.master_switch
        from: "off"
        to: "on"
    condition:
      # vacation mode can trigger master switch to on
      - condition: state
        entity_id: input_boolean.vacation
        state: "off"
    action:
      - service: switch.turn_off
        entity_id: switch.foscam_r2m_one_motion
      # - service: foscam.ptz_preset
      #   entity_id: camera.foscam_r2m_one
      #   data:
      #     preset_name: Park

  - id: camera_front_door_motion_detection_enable
    alias: Camera - Enable motion detection
    description: Enable the camera surveillance when leaving home, at night or when on vacation
    trigger:
      - platform: state
        entity_id: input_boolean.master_switch
        from: "on"
        to: "off"
        for:
          minutes: 2
      - platform: state
        entity_id: input_boolean.vacation
        from: "off"
        to: "on"
        for:
          minutes: 5
      - platform: homeassistant
        event: start
    action:
      # - service: foscam.ptz_preset
      #   entity_id: camera.foscam_r2m_one
      #   data:
      #     preset_name: Hall
      - delay: 30 # make sure the camera has stopped moving (it shouldn't detect motion while moving but still ...)
      - service: switch.turn_on
        entity_id: switch.foscam_r2m_one_motion
