---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   01/2022
#   @package        :   Front door camera on motion
#   @description    :   Triggers some camera related actions on motion
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################

automation:
  - id: camera_person_detected
    alias: Camera - Person detected
    mode: single
    trigger:
      - platform: mqtt
        topic: frigate/events
    condition:
      - condition: or
        conditions:
          - alias: Master switch off and button_toggle_master_switch_off not running still
            condition: and
            conditions:
              - condition: state
                entity_id: input_boolean.master_switch
                state: "off"
              - condition: numeric_state
                entity_id: automation.button_toggle_master_switch_off
                attribute: current
                below: 1
          - alias: On vacation, trigger always
            condition: state
            entity_id: input_boolean.vacation
            state: "on"
      - "{{ trigger.payload_json['after']['label'] == 'person' }}"
      - "{{ as_local(state_attr('automation.button_toggle_master_switch_off', 'last_triggered')) < (now() - timedelta(minutes = 5)) }}"
    action:
      - service: script.turn_on
        target: 
          entity_id: script.camera_motion_detected_script
        data:
          variables:
            camera: "{{ trigger.payload_json['after']['camera'] }}"
            event_id: "{{ trigger.payload_json['after']['id'] }}"


script:
  camera_motion_detected_script:
    description: Notify on motion if not detected home within 5 minutes
    mode: single
    sequence:
      - wait_for_trigger:
          - platform: state
            entity_id: group.household_members
            to: home
        timeout: "00:05:00"
        continue_on_timeout: true
      - condition: state
        alias: Check if nobody is home
        entity_id: group.household_members
        state: not_home
      - service: notify.mobile_app_pwxperia10iv
        data:
          message: |
            It is {{ as_timestamp(now()) | timestamp_custom('%a %B %-m, %I:%M %p') }}
          title: Motion detected by {{ camera }}
          data:
            sticky: true
            image: https://homeassistant.pwcasa.local/api/frigate/notifications/{{ event_id }}/snapshot.jpg?format=android
            actions:
              - action: URI
                title: "View clip"
                uri: https://homeassistant.pwcasa.local/api/frigate/notifications/{{ event_id }}/clip.mp4
      - delay: 1800 # do no spam me with notifications
