---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   01/2022
#   @package        :   Front door camera on motion
#   @description    :   Triggers some camera related actions on motion
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################

automation:
  - id: camera_front_door_on_motion_detected
    alias: Camera - Notify on motion
    mode: single
    description: Take snapshot from camera and notify in case of motion
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_presence
        to: "on"
        from: "off"
    condition:
      - condition: state
        entity_id: switch.foscam_r2m_one_motion
        state: "on"
      - alias: "Button triggered long enough ago"
        condition: template
        value_template: "{{ (as_timestamp(now()) - as_timestamp(state_attr('automation.button_toggle_master_switch_off', 'last_triggered'))) > 300 }}"
      - condition: or
        conditions:
          - alias: Master switch off and button_toggle_master_switch_off not running still
            condition: and
            conditions:
              - condition: state
                entity_id: input_boolean.master_switch
                state: "off"
              - condition: numeric_state
                entity_id: automation.button_toggle_master_switch_off
                attribute: current
                below: 1
          - alias: On vacation, trigger always
            condition: state
            entity_id: input_boolean.vacation
            state: "on"
    action:
      - service: script.camera_front_door_on_motion_detected_script

  - id: camera_front_door_on_motion_detected_snapshot_loop
    alias: Camera - Take snapshots to media folder on motion
    description: Take snapshot from camera and store in media folder (can run more frequently)
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_presence
        to: "on"
        from: "off"
    condition:
      - condition: state
        entity_id: switch.foscam_r2m_one_motion
        state: "on"
      - alias: Only run it when motion is detected (steps out of the loop)
        condition: state
        entity_id: binary_sensor.front_door_presence
        state: "on"
      - condition: or
        conditions:
          - alias: Master switch off and button_toggle_master_switch_off not running still
            condition: and
            conditions:
              - condition: state
                entity_id: input_boolean.master_switch
                state: "off"
              - condition: numeric_state
                entity_id: automation.button_toggle_master_switch_off
                attribute: current
                below: 1
          - alias: On vacation, trigger always
            condition: state
            entity_id: input_boolean.vacation
            state: "on"
    action:
      - service: script.camera_front_door_on_motion_detected_snapshot_loop_script

script:
  camera_front_door_on_motion_detected_script:
    description: Captures hall camera when motion is detected and notify if not home in 5 min
    mode: single
    sequence:
      - service: camera.snapshot
        alias: Take snapshot for notification
        data:
          filename: /config/www/snap_hall.jpg
        target:
          entity_id: camera.r2m_1_onvif_prof0_name
      - service: camera.record
        target:
          entity_id: camera.r2m_1_onvif_prof0_name
        data:
          duration: 15
          filename: >-
            /media/snap_{{ as_timestamp(now()) | timestamp_custom('%Y_%m_%d_%H_%M')
            }}.mp4
      - wait_for_trigger:
          - platform: state
            entity_id: group.household_members
            to: home
        timeout: "00:07:00"
        continue_on_timeout: true
      - condition: state
        alias: Check if nobody is home
        entity_id: group.household_members
        state: not_home
      - service: notify.mobile_app_pwxperia10iv
        data:
          message: |
            It is {{ as_timestamp(now()) | timestamp_custom('%a %B %-m, %I:%M %p') }}
          title: Motion detected in hallway
          data:
            sticky: true
            image: https://homeassistant.pwcasa.local/local/snap_hall.jpg
      - delay: 1800 # do no spam me with notifications (and keep HA's cost low)

  camera_front_door_on_motion_detected_snapshot_loop_script:
    description: Make multiple captures when motion is detected
    mode: single
    sequence:
      repeat:
        sequence:
          - service: camera.snapshot
            alias: Take a snapshot for storage
            data:
              filename: /media/snap_{{ as_timestamp(now()) | timestamp_custom('%Y_%m_%d_%H_%M') }}.jpg
            target:
              entity_id: camera.r2m_1_onvif_prof0_name
          - delay: 5
        until:
          - condition: or
            conditions:
              - condition: state
                entity_id: group.household_members
                state: home
              - condition: state
                entity_id: input_boolean.master_switch
                state: "on"
              - condition: state
                entity_id: binary_sensor.front_door_presence
                state: "off"
