---
# dryer
substitutions:
  plug_name: gosund-sp1-1
  plug_id: gosund_sp1_1
  ip: 10.0.2.41
  # Higher value gives lower watt readout
  current_res: "0.00200"
  # Lower value gives lower voltage readout
  voltage_div: "945"
  comment: Dryer switch

esphome:
  name: ${plug_name}
  comment: ${comment}
  platform: ESP8266
  board: esp8285

# WiFi connection
wifi:
  ssid: !secret new_wifi_ssid
  password: !secret new_wifi_password
  fast_connect: true
  reboot_timeout: 6h
  power_save_mode: high
  manual_ip:
    static_ip: ${ip}
    gateway: 10.0.0.1
    subnet: 255.255.0.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${plug_name} Fallback Hotspot"
    password: !secret ap_password
    ap_timeout: 15min

captive_portal:

# Enable logging
logger:
  logs:
    sensor: INFO
    adc: INFO
    hlw8012: INFO
    
# Enable Home Assistant API
api:
  reboot_timeout: 8h
  encryption:
    key: !secret encryption_key

# Enable over-the-air updates
ota:
  platform: esphome
  password: !secret ota_password
  
time:
  - platform: homeassistant
    id: homeassistant_time

# Enable Web server
#web_server:
# port: 80

sensor:
  # Power sensor
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    change_mode_every: 3
    update_interval: 5s
    # Current sensor
    current:
      id: ${plug_id}_current
      name: ${plug_name} Current
      unit_of_measurement: A
      accuracy_decimals: 2
      filters:
        # Map from sensor -> measured value
        - calibrate_linear:
          - 0.0 -> 0.0
          - 0.067 -> 0.09
          - 2.11 -> 2.83
          - 4.063 -> 6.36
        - lambda: if (x < 0.01) return 0; else return x;
        - sliding_window_moving_average:
            window_size: 5
            send_every: 12
    # Voltage sensor
    voltage:
      id: ${plug_id}_voltage
      name: ${plug_name} Voltage
      unit_of_measurement: V
      accuracy_decimals: 0
      filters:
        # Map from sensor -> measured value
        - calibrate_linear:
           - 0.0 -> 0.0
           - 218.1 -> 218
        - throttle: 120s
    # Power sensor
    power:
      id: ${plug_id}_wattage
      name: ${plug_name} Wattage
      unit_of_measurement: W
      accuracy_decimals: 1
      filters:
        # Map from sensor -> actual value
        - calibrate_linear:
           - 0.0 -> 0
           - 7.1 -> 6.1
           - 27 -> 23.6
           - 41.6 -> 37.3
           - 331 -> 283
           - 896.8 -> 796
           - 1572 -> 1415
        # Add the power consumtion of the plug
        - lambda: |
            if (id(${plug_id}_relay).state)
              if (x < 0)
                return 1.2;
              else
                return 1.2 + x;
            else
              if (x < 0)
                return 0.6;
              else 
                return 0.6 + x;
        - sliding_window_moving_average:
            window_size: 3
            send_every: 5
    energy:
      id: ${plug_id}_total_energy
      name: ${plug_name} Consumption

  - platform: total_daily_energy
    name: ${plug_name} Total Daily Energy Consumption
    power_id: ${plug_id}_wattage
    id: ${plug_id}_total_daily_energy
    filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
    unit_of_measurement: kWh
    device_class: energy
      
  - platform: wifi_signal
    name: "${plug_name} RSSI"
    update_interval: 120s
    unit_of_measurement: dBm

binary_sensor:
  # Binary sensor for the button press
  - platform: gpio
    name: "${plug_name} Button"
    pin:
      number: GPIO3
      inverted: true
    on_press:
      - switch.toggle: ${plug_id}_relay

switch:
  # Switch to toggle the relay
  - platform: gpio
    id: ${plug_id}_relay
    name: "${plug_name} Main relay"
    pin: GPIO14
    restore_mode: RESTORE_DEFAULT_ON 
    on_turn_on:
      - light.turn_on: ${plug_id}_led
    on_turn_off:
      - light.turn_off: ${plug_id}_led

output:
  # Relay state led
  - platform: esp8266_pwm
    id: ${plug_id}_state_led
    pin:
      number: GPIO13
      inverted: true

light:
  # Relay state light
  - platform: monochromatic
    output: ${plug_id}_state_led
    id: ${plug_id}_led
    restore_mode: RESTORE_DEFAULT_ON 

# Uses the red BLUE as a status indicator
status_led:
  pin:
    number: GPIO1
    inverted: true

