###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   04/2021
#   @package        :   General System Configuration
#   @description    :   Contains system related sensors and automations
#   @url            :
###############################################################################

sensor:
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    # If errors occur, make sure configuration file is encoded as UTF-8
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(0) }}'

  - platform: command_line
    name: GPU Temperature
    command: "/opt/vc/bin/vcgencmd measure_temp | sed 's/temp=//g' | sed \"s/'C//g\""
    # If errors occur, make sure configuration file is encoded as UTF-8
    unit_of_measurement: "°C"
    value_template: '{{ value | float | round(0) }}'

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use_percent
        arg: /srv
      - type: disk_use_percent
        arg: /home
      - type: load_1m
      - type: processor_use
      - type: last_boot

automation:
# next: 17
  - id: '8000000000000'
    alias: System - Set Custom Theme at Startup
    description: Set the default theme for all users on startup
    trigger:
      platform: homeassistant
      event: start
    action:
      service: frontend.set_theme
      data:
        name: ios-light-mode-orange-alternative

  ## weekly full snapshot ##
  - id: '8000000000012'
    alias: System - Snapshot full
    description: Takes a full snapshot every week on Monday
    trigger:
    - platform: time
      at: '04:00:00'
    condition:
    - condition: time
      weekday:
        - mon
    action:
    - service: hassio.snapshot_full

  ## Weekly reboot, if we don't reboot every week, how do we know a restart is a safe operation ? ##
  - id: '8000000000014'
    alias: System - Reboot
    description: Reboots the system every week on Wednesday
    trigger:
    - platform: time
      at: '02:00:00'
    condition:
    - condition: time
      weekday:
        - wed
    action:
    - service: hassio.host_reboot


  - id: '8000000000015'
    alias: Button - Toggle evening lights
    description: Use center button to toggle evening mode
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: 'lightify_switch_mini_27'
          event: 3002
    condition:
      - condition: state
        entity_id: input_boolean.master_switch
        state:  'on'
    action:
      - service: input_boolean.toggle
        data:
          entity_id: input_boolean.dusk_till_dawn

  - id: '8000000000016'
    alias: Button - Toggle dimmed lights
    description: Use down button to turn on evening mode and toggle dimmed mode
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: 'lightify_switch_mini_27'
          event: 2002
    condition:
      - condition: state
        entity_id: input_boolean.master_switch
        state:  'on'
    action:
      - service: input_boolean.toggle
        data:
          entity_id: input_boolean.dimm_lights
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.dusk_till_dawn