###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   04/2021
#   @package        :   Foscam camera integration
#   @description    :   Foscam motion sensor control
#   @url            :   https://github.com/PW999/home-assistant-config/
#   @credit         :   TODO
###############################################################################

# TODO:
# [ ] Site source (find it first, should have noted it when I used it)
# [X] Use dusk_till_dawn switch instead of fixed times
# [X] Format date time better in notification
# [X] Add secret templates to this yaml

# Command lines used in this template to get data from the camera using the XML API
# I do not have motion detection enabled in all area's
# foscam_r2m_one_motion_on_url: 'curl -k --tls-max 1.2 "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=1&snapInterval=3&sensitivity=3&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=960&area1=960&area2=960&area3=960&area4=960&area5=960&area6=992&area7=1016&area8=1020&area9=1023&linkage=12&usr=ADMIN&pwd=PASSWD"'
# foscam_r2m_one_motion_off_url: 'curl -k --tls-max 1.2 "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=0&usr=ADMIN&pwd=PASSWD"'
# foscam_r2m_one_motion_state_url:  'curl -k --silent --tls-max 1.2 "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=getMotionDetectConfig&usr=ADMIN&pwd=PASSWD" | grep "isEnable" | cut -b 15'
# foscam_r2m_one_motion_detected_url: curl -k --silent --tls-max 1.2 "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=getDevState&usr=ADMIN&pwd=PASSWD" | grep "motionDetectAlarm" | cut -b 24
# 
# foscam_r2m_one_infrared_off_url: 'curl -k --tls-max 1.2 "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=closeInfraLed&usr=ADMIN&pwd=PASSWD"'
# foscam_r2m_one_infrared_on_url: 'curl -k --tls-max 1.2 "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=openInfraLed&usr=ADMIN&pwd=PASSWD"'
# foscam_r2m_one_infrared_state_url: 'curl -k --silent --tls-max 1.2 "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=getDevState&usr=ADMIN&pwd=PASSWD" | grep "infraLedState" | cut -b 20'
# 
# Gets the log events and translates the event id's to something more human readable
# foscam_r2m_one_log_0: curl -s -k --tls-max 1.2 "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=getLog&usr=ADMIN&pwd=PASSWD" | sed 's/%2B/ /g' | grep log0 | sed 's/<\/*log[0-9]>//g' | awk '{split($0,a); b = strftime("%d/%m/%Y %H:%M:%S", a[1], 1); c = a[4]; if (c == "1") { c="Motion"}; if (c == "3") { c = "Login " a[2] }; if (c == "4") { c="Logout " a[2]}; print b " " c; }'
# foscam_r2m_one_log_1: curl -s -k --tls-max 1.2 "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=getLog&usr=ADMIN&pwd=PASSWD" | sed 's/%2B/ /g' | grep log1 | sed 's/<\/*log[0-9]>//g' | awk '{split($0,a); b = strftime("%d/%m/%Y %H:%M:%S", a[1], 1); c = a[4]; if (c == "1") { c="Motion"}; if (c == "3") { c = "Login " a[2] }; if (c == "4") { c="Logout " a[2]}; print b " " c; }'
# foscam_r2m_one_log_2: curl -s -k --tls-max 1.2 "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=getLog&usr=ADMIN&pwd=PASSWD" | sed 's/%2B/ /g' | grep log2 | sed 's/<\/*log[0-9]>//g' | awk '{split($0,a); b = strftime("%d/%m/%Y %H:%M:%S", a[1], 1); c = a[4]; if (c == "1") { c="Motion"}; if (c == "3") { c = "Login " a[2] }; if (c == "4") { c="Logout " a[2]}; print b " " c; }'
# foscam_r2m_one_log_3: curl -s -k --tls-max 1.2 "https://IP-ADDRESS:443/cgi-bin/CGIProxy.fcgi?cmd=getLog&usr=ADMIN&pwd=PASSWD" | sed 's/%2B/ /g' | grep log3 | sed 's/<\/*log[0-9]>//g' | awk '{split($0,a); b = strftime("%d/%m/%Y %H:%M:%S", a[1], 1); c = a[4]; if (c == "1") { c="Motion"}; if (c == "3") { c = "Login " a[2] }; if (c == "4") { c="Logout " a[2]}; print b " " c; }'


homeassistant:
  customize:
    sensor.foscam_r2m_1_log0:
      icon: mdi:post
    sensor.foscam_r2m_1_log1:
      icon: mdi:post
    sensor.foscam_r2m_1_log2:
      icon: mdi:post
    sensor.foscam_r2m_1_log3:
      icon: mdi:post
    sensor.foscam_r2m_1_motion_detected:
      icon: mdi:motion-sensor
    switch.foscam_r2m_one_motion:
      icon: mdi:cctv
    switch.foscam_r2m_one_infrared:
      icon: mdi:cctv
sensor:
    # Read the logs so we can show a history of motion detections. Sensor value length
    # is only limited, so one sensor per log line.
  - platform: command_line
    name: Foscam R2M-1 log0
    scan_interval: 300
    command: !secret foscam_r2m_one_log_0
  - platform: command_line
    name: Foscam R2M-1 log1
    scan_interval: 300
    command: !secret foscam_r2m_one_log_1
  - platform: command_line
    name: Foscam R2M-1 log2
    scan_interval: 300
    command: !secret foscam_r2m_one_log_2
  - platform: command_line
    name: Foscam R2M-1 log3
    scan_interval: 300
    command: !secret foscam_r2m_one_log_3

    # Check if Foscam camera detected motion.
  - platform: command_line
    name: Foscam R2M-1 Motion Detected
    scan_interval: 2
    command: !secret foscam_r2m_one_motion_detected_url
    value_template: '{{ value == "2" }}'

input_boolean:
  foscam_r2m_1_motion_detected_smooth:
    name: Foscam R2M-1 Motion Detected
    icon: mdi:motion-sensor

switch:
  - platform: command_line
    switches:
      #Switch for Foscam Motion Detection
      foscam_r2m_one_motion:
        friendly_name : Foscam R2M-1 Motion Sensor
        command_on: !secret foscam_r2m_one_motion_on_url
        command_off: !secret foscam_r2m_one_motion_off_url
        command_state: !secret foscam_r2m_one_motion_state_url
        value_template: '{{ value == "1" }}'
      foscam_r2m_one_infrared:
        friendly_name : Foscam R2M-1 Infrared
        command_on: !secret foscam_r2m_one_infrared_on_url
        command_off: !secret foscam_r2m_one_infrared_off_url
        command_state: !secret foscam_r2m_one_infrared_state_url
        value_template: '{{ value == "1" }}'

##############################################
# Handle camera's (8000000011xxx)
##############################################
# NEXT_ID 9

automation:
  - id: '8000000011001'
    alias: Camera - Disable motion detection when home
    description: Disable the camera surveillance when home
    trigger:
      - platform: state
        entity_id: input_boolean.master_switch
        from: 'off'
        to: 'on'
    condition:
      # vacation mode can trigger master switch to on
      - condition: state
        entity_id: input_boolean.vacation
        state: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.foscam_r2m_one_motion
      - service: foscam.ptz_preset
        entity_id: camera.foscam_r2m_one
        data:
          preset_name: Park


  - id: '8000000011002'
    alias: Camera - Enable motion detection when not home
    description: Enable the camera surveillance when leaving home, at night or when on vacation
    trigger:
      - platform: state
        entity_id: input_boolean.master_switch
        from: 'on'
        to: 'off'
        for:
          minutes: 2
      - platform: state
        entity_id: input_boolean.vacation
        from: 'off'
        to: 'on'
        for:
          minutes: 2
    action:
      - service: foscam.ptz_preset
        entity_id: camera.foscam_r2m_one
        data:
          preset_name: Hall
      - delay: 30   # make sure the camera has stopped moving (it shouldn't detect motion while moving but still ...)
      - service: switch.turn_on
        entity_id: switch.foscam_r2m_one_motion

  - id: '8000000011003'
    alias: Camera - Infrared on
    description: Enable camera infrared when it's getting dark and motion detection is active
    trigger:
      - platform: state
        entity_id: switch.foscam_r2m_one_motion
        to: 'on'
      - platform: state
        entity_id: input_boolean.dusk_till_dawn
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.dusk_till_dawn
        state: 'on'
      - condition: state
        entity_id: switch.foscam_r2m_one_motion
        state: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.foscam_r2m_one_infrared

  - id: '8000000011004'
    alias: Camera - Infrared off
    description: Disable camera infrared when it's light or motion detection is disabled
    trigger:
      - platform: state
        entity_id: switch.foscam_r2m_one_motion
        to: 'off'
      - platform: state
        entity_id: input_boolean.dusk_till_dawn
        to: 'off'
    condition:
      - condition: or
        conditions:
        - condition: state
          entity_id: input_boolean.dusk_till_dawn
          state: 'off'
        - condition: state
          entity_id: switch.foscam_r2m_one_motion
          state: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.foscam_r2m_one_infrared

  - id: '8000000011005'
    alias: Camera - Notify on motion
    mode: single
    description: Take snapshot from camera and notify in case of motion
    trigger:
      - platform: state
        entity_id: input_boolean.foscam_r2m_1_motion_detected_smooth
        to: 'on'
        for: 00:00:04
    action:
      - service: camera.snapshot
        alias: 'Take snapshot for notification'
        data:
          filename: /config/www/snap_hall.jpg
        target:
          entity_id: camera.foscam_r2m_one
      - delay: 5  # make sure the file is properly written
      - service: notify.mobile_app_mi_9t
        data:
          message: |
            It is {{ as_timestamp(now()) | timestamp_custom('%a %B %-m, %I:%M %p') }}
          title: Motion detected in hallway
          data:
            sticky: true
            image: "http://192.168.0.16:8123/local/snap_hall.jpg"
      - delay: 3600  # do no spam me with notifications (and keep HA's cost low)

  - id: '8000000011006'
    alias: Camera - Take snapshot to media folder on motion
    mode: single
    description: Take snapshot from camera and store in media folder (can run more frequently)
    trigger:
      - platform: state
        entity_id: input_boolean.foscam_r2m_1_motion_detected_smooth
        to: 'on'
        for: 00:00:04
    condition:
      - alias: Only run it when motion is detected (steps out of the loop)
        condition: state
        entity_id: input_boolean.foscam_r2m_1_motion_detected_smooth
        state: 'on'
    action:
      - service: camera.snapshot
        alias: 'Take a snapshot for storage'
        data:
          filename: /media/snap_{{ as_timestamp(now()) | timestamp_custom('%Y_%m_%d_%H_%M') }}.jpg
        target:
          entity_id: camera.foscam_r2m_one
      - delay: 5
      - service: automation.trigger # (loop)
        target:
          entity_id: automation.camera_take_snapshot_to_media_folder_on_motion

  - id: '8000000011007'
    alias: Camera - Motion detected (dejitter)
    description: Motion detected, act immediately
    trigger:
      - platform: state
        entity_id: sensor.foscam_r2m_1_motion_detected
        from: 'False'
        to: 'True'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.foscam_r2m_1_motion_detected_smooth

  - id: '8000000011008'
    alias: Camera - No more motion detected (dejitter)
    description: No motion detected anymore, wait for another confirm
    trigger:
      - platform: state
        entity_id: sensor.foscam_r2m_1_motion_detected
        from: 'True'
        to: 'False'
        for: 00:00:04
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.foscam_r2m_1_motion_detected_smooth