---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   01/2022
#   @package        :   Bathroom fan automation
#   @description    :   Triggers the bathroom fan
#   @url            :   https://codeberg.org/PW999/home-assistant-config/
###############################################################################

homeassistant:
  customize:
    switch.bathroom_fan_switch:
      icon: mdi:fan

automation:
  - id: humidity_bathroom_fan_on
    alias: Bathroom fan - turn on
    description: Turn the bathroom fan on if is too humid in the house or if dryer is on
    triggers:
      - entity_id: sensor.bathroom_sensor_humidity
        trigger: numeric_state
        above: 68
      - entity_id: sensor.office_humidity_at_20
        trigger: numeric_state
        above: 68
      - entity_id: sensor.living_room_humidity_at_20
        trigger: numeric_state
        above: 68
      - trigger: state
        entity_id: sensor.dryer_status
        to: Running
        for: "00:15:00"   # do not turn it on immediately, humidity won't rise this fast
    actions:
      - action: switch.turn_on
        data:
          entity_id: switch.bathroom_fan_switch
      - action: logbook.log
        data:
          name: humidity_bathroom_fan_on
          message: Bathroom fan turned on by {{ trigger.entity_id }}
          entity_id: sensor.bathroom_sensor_humidity
          domain: sensor
      - action: logbook.log
        data:
          name: humidity_bathroom_fan_on
          message: Bathroom fan turned on by {{ trigger.entity_id }}
          entity_id: sensor.living_room_humidity_at_20
          domain: sensor
      - action: logbook.log
        data:
          name: humidity_bathroom_fan_on
          message: Bathroom fan turned on by {{ trigger.entity_id }}
          entity_id: sensor.office_humidity_at_20
          domain: sensor

  - id: humidity_bathroom_fan_off
    alias: Bathroom fan - turn off
    description: Turn the bathroom fan off base on humidity, dryer state of after a time-out
    triggers:
      - entity_id: sensor.bathroom_sensor_humidity
        trigger: numeric_state
        below: 65
        for: "00:10:00"
      - entity_id: sensor.office_humidity_at_20
        trigger: numeric_state
        below: 67
        for: "00:10:00"
      - entity_id: sensor.living_room_humidity_at_20
        trigger: numeric_state
        below: 67
        for: "00:10:00"
      - entity_id: switch.bathroom_fan_switch
        trigger: state
        to: "on"
        for: "00:30:00"
      - trigger: state
        entity_id: sensor.dryer_status
        from: Running
        for: "00:20:00"   # give it some de-bounce time and after run time
    conditions:
      - condition: not
        conditions:
          - alias: Keep the fan on while the dryer is on
            condition: state
            entity_id: sensor.dryer_status
            state: Running
    actions:
      - action: switch.turn_off
        data:
          entity_id: switch.bathroom_fan_switch
