---

# ##############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   01/2022
#   @package        :   humidity
#   @description    :   Create absolute humidity sensors and alert in case of too dry/humid
#   @url            :   https://github.com/PW999/home-assistant-config/
#   @credit         :   https://carnotcycle.wordpress.com/2012/08/04/how-to-convert-relative-humidity-to-absolute-humidity/
#   @erb            :   ./humidity/template/humidity_bedroom.erb
# ##############################################################################


# First create a bunch of sensors with the absolute humidity based on the relative humidity and the temperature.
# For simplicity sake, the current air pressure is ignored (it should be less than 1% off the actual value, I think)
# Then create a sensor which calculate the relative humidity if it were 20째c. Relative humidity is more
# "human readable" and this value allows us to check of the relative humidity changed due to temperature changes
# (so the amount of water in the air doesn't change) or if we really had a change in the amount of moisture in the air.
sensor:
  - platform: template
    sensors:
      bedroom_absolute_humidity:
        friendly_name: Bedroom absolute humidity
        unique_id: humidity_bedroom_sensor_absolute_humidity
        icon_template: mdi:water
        availability_template: >-
            {{ not (
                  is_state('sensor.bedroom_sensor_temperature', 'unavailable')
                  or is_state('sensor.bedroom_sensor_humidity', 'unavailable')
                  or is_state('sensor.bedroom_sensor_temperature', 'unknown')
                  or is_state('sensor.bedroom_sensor_humidity', 'unknown')
                )
            }}
        value_template: >-
            {{
            ( float(6.112) * e**( (( float(17.67) * float(states('sensor.bedroom_sensor_temperature')) )/(  float(states('sensor.bedroom_sensor_temperature')) + float(243.5) ))) * ( float(states('sensor.bedroom_sensor_humidity')) / 100 ) * float(18.02)  )
            /
            ( ( float(states('sensor.bedroom_sensor_temperature')) + 273.5) * float(100.0) * float(0.08314) )
            }}
      bedroom_humidity_at_20:
        friendly_name: Bedroom humidity at 20째c
        unique_id: humidity_bedroom_sensor_humidity_at_20
        unit_of_measurement: "%"
        device_class: humidity
        availability_template: "{{ not is_state('sensor.bedroom_absolute_humidity', 'unavailable') and is_number(states('sensor.bedroom_absolute_humidity')) }}"
        value_template: "{{ (float(states('sensor.bedroom_absolute_humidity')) * 5.788 * 100.0) | round(0) }}"


automation:
  - id: humidity_bedroom_automation_humidity_too_high
    alias: Notification - Bedroom humidity too high
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.bedroom_sensor_humidity
        above: 75
        for: "00:10:00"
      - platform: state
        entity_id: sensor.terrace_sensor_humidity
      - platform: state
        entity_id: input_boolean.master_switch
        to: "on"
        for: "00:15:00"
    condition:
      - condition: numeric_state
        entity_id: sensor.bedroom_sensor_temperature
        above: 16   # 70% @ 15째c == 52% @ 20째c
      - condition: numeric_state
        entity_id: sensor.bedroom_sensor_humidity
        above: 75
      - condition: state
        entity_id: input_boolean.master_switch
        state: "on"
      - condition: or
        conditions:
          - alias: Trigger when I get home or wake up
            condition: template
            value_template: "{{ trigger.entity_id == 'input_boolean.master_switch' }}"
          - alias: Trigger when bedroom humidity rises from below to above threshold
            condition: template
            value_template: "{{ trigger.entity_id == 'sensor.bedroom_sensor_humidity' and (trigger.from_state.state | float(100)) <= 75.0 }}"
          - alias: Trigger when outside humidity lowers
            condition: template
            value_template: "{{ trigger.entity_id == 'sensor.terrace_sensor_humidity' and (trigger.from_state.state | float(0)) > (trigger.to_state.state | float(100)) }}"
      - alias: If outside humidity is much lower than inside humidity
        condition: template
        value_template: >
          {{ ( float(states('sensor.bedroom_humidity_at_20')) - float(states('sensor.terrace_humidity_at_20')) ) >= 15 }}
    action:
      - service: notify.mobile_app_pwxperia10iv
        data:
          message: |
            Relative humidity is {{ float(states('sensor.bedroom_sensor_humidity')) }}%, consider opening a window.
            Debug: IN: {{ float(states('sensor.bedroom_humidity_at_20'))}} - OUT: {{float(states('sensor.terrace_humidity_at_20'))}}
          title: Bedroom humidity warning
      - delay: 7200


  - id: humidity_bedroom_automation_humidity_too_low
    alias: Notification - Bedroom humidity too low
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.bedroom_sensor_humidity
        below: 40
        for: "00:10:00"
    condition:
      - alias: Only if we cross the treshold
        condition: template
        value_template: >
          {%  if trigger.entity_id != 'sensor.bedroom_sensor_humidity'  %}
          false
          {% else %}
          {{ trigger.from_state.state | float >= 40.0   }}
          {% endif %}
      - condition: numeric_state
        entity_id: sensor.bedroom_sensor_humidity
        below: 40
    action:
      - service: notify.mobile_app_pwxperia10iv
        data:
          message: |
            Relative humidity is at {{ float(states('sensor.bedroom_sensor_humidity')) }}% !
          title: Bedroom humidity warning
      - delay: 7200
