---

# ##############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   01/2022
#   @package        :   humidity
#   @description    :   Create additional humidity related sensors
#   @url            :   https://github.com/PW999/home-assistant-config/
#   @credit         :   https://carnotcycle.wordpress.com/2012/08/04/how-to-convert-relative-humidity-to-absolute-humidity/
#   @erb            :   ./humidity/template/terrace.erb
# ##############################################################################

# First create a bunch of sensors with the absolute humidity based on the relative humidity and the temperature.
# For simplicity sake, the current air pressure is ignored (it should be less than 1% off the actual value, I think)
# Then create a sensor which calculate the relative humidity if it were 20°c. Relative humidity is more
# "human readable" and this value allows us to check of the relative humidity changed due to temperature changes
# (so the amount of water in the air doesn't change) or if we really had a change in the amount of moisture in the air.
sensor:
  - platform: template
    sensors:
      terrace_absolute_humidity:
        friendly_name: terrace absolute humidity
        unique_id: humidity_terrace_sensor_absolute_humidity
        icon_template: mdi:water
        availability_template: >-
            {{ not (
                  is_state('sensor.terrace', 'unavailable')
                  or is_state('sensor.terrace_2', 'unavailable')
                  or is_state('sensor.terrace', 'unknown')
                  or is_state('sensor.terrace_2', 'unknown')
                )
            }}
        value_template: >-
            {{
            ( float(6.112) * e**( (( float(17.67) * float(states('sensor.terrace')) )/(  float(states('sensor.terrace')) + float(243.5) ))) * ( float(states('sensor.terrace_2')) / 100 ) * float(18.02)  )
            /
            ( ( float(states('sensor.terrace')) + 273.5) * float(100.0) * float(0.08314) )
            }}
      terrace_humidity_at_20:
        friendly_name: terrace humidity at 20°c
        unique_id: humidity_terrace_sensor_humidity_at_20
        unit_of_measurement: "%"
        device_class: humidity
        availability_template: "{{ not is_state('sensor.terrace_absolute_humidity', 'unavailable') and is_number(states('sensor.terrace_absolute_humidity')) }}"
        value_template: "{{ (float(states('sensor.terrace_absolute_humidity')) * 5.788 * 100.0) | round(0) }}"
