---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   04/2021
#   @package        :   General System Configuration
#   @description    :   Creates a weekly backup
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################

automation:
  ## weekly full snapshot ##
  - id: system_automatic_backup
    alias: System - Full backup
    description: Takes a full backup every week on Monday
    trigger:
      - platform: time
        at: "04:00:00"
    condition:
      - condition: time
        weekday:
          - mon
    action:
      - service: hassio.backup_full
