---
###############################################################################
#   @author         :   Phillip (P_W999)
#   @date           :   04/2021
#   @package        :   General System Configuration
#   @description    :   Creates a weekly backup
#   @url            :   https://github.com/PW999/home-assistant-config/
###############################################################################

automation:
  ## weekly full snapshot ##
  - id: system_automatic_backup
    alias: System - Full backup
    description: Takes a full backup every week on Monday
    triggers:
      - trigger: time
        at: "04:00:00"
    conditions:
      - condition: time
        weekday:
          - mon
    action:
      - action: hassio.backup_full
